# **CLUSTERING NOTEBOOK**

## Libraries

In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from umap.umap_ import UMAP
from sklearn.metrics import silhouette_samples, silhouette_score
import matplotlib.cm as cm
from sklearn.decomposition import PCA
import plotly.express as px
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [63]:
import sys
import os

# Get the absolute path of the source_code folder
source_code_path = os.path.abspath('../source_code')

# Add the source_code folder to sys.path
if source_code_path not in sys.path:
    sys.path.append(source_code_path)

from utils import *
from preprocessing import *
from clustering import *
from analysis import *

# Get the absolute path of the source_code folder
clustering_outputs_path = os.path.abspath('../clustering_outputs')

# Add the source_code folder to sys.path
if clustering_outputs_path not in sys.path:
    sys.path.append(clustering_outputs_path)

## Load Data

In [64]:
customer_info = load_dataset('../customer_info.csv')

In [65]:
#customer_info.columns

In [66]:
# Calling the clusters
final_clustering_notcaled=load_dataset('../clustering_outputs/final_clustering_notscaled.csv')
final_clustering = load_dataset('../clustering_outputs/final_clustering.csv')

In [67]:
customer_basket = load_dataset('../customer_basket.csv')

## Analysis

In [7]:
vars, cluster_avg, database_avg=compute_average_multi(hierarchical8_scaled, 'cluster')

In [8]:
plot_all_clusters_profile_plotly(vars, cluster_avg, database_avg)

## Association Rules

In [74]:
df_items0, items_list0 = transform_dataset(customer_basket, final_clustering,1)

KeyError: "None of ['customer_id'] are in the columns"

In [75]:
df_items0, items_list0

(     airpods  almonds  antioxydant juice  asparagus  avocado  babies food  \
 0      False    False              False       True    False        False
 1      False    False              False      False    False        False
 2      False    False              False      False    False        False
 3      False    False              False      False    False        False
 4      False    False              False      False    False        False
 ..       ...      ...                ...        ...      ...          ...
 291    False    False              False      False    False        False
 292    False    False              False      False    False        False
 293    False    False              False      False    False        False
 294    False    False              False      False    False        False
 295    False    False              False      False    False        False

      bacon  barbecue sauce   beer  black beer  ...  vacuum cleaner  \
 0    False           False  False       False  ...           False
 1     True           False  False       False  ...           False
 2    False           False  False       False  ...           False
 3    False           False   True       False  ...            True
 4    False           False  False       False  ...           False
 ..     ...             ...    ...         ...  ...             ...
 291  False            True  False       False  ...           False
 292  False           False  False       False  ...           False
 293  False           False  False       False  ...           False
 294  False           False  False       False  ...           False
 295  False           False   True       False  ...           False

      vegetables mix  water spray  white wine  whole weat flour  \
 0             False        False       False             False
 1             False        False       False              True
 2              True        False       False             False
 3             False        False       False             False
 4             False        False        True             False
 ..              ...          ...         ...               ...
 291           False        False        True             False
 292           False        False       False             False
 293           False        False       False             False
 294           False        False       False             False
 295           False        False       False             False

      whole wheat pasta  whole wheat rice   yams  yogurt cake  zucchini
 0                False             False  False        False     False
 1                False             False  False        False     False
 2                False             False  False        False     False
 3                False             False  False         True     False
 4                False             False  False        False     False
 ..                 ...               ...    ...          ...       ...
 291              False             False  False        False     False
 292              False             False  False        False     False
 293              False             False  False        False     False
 294              False             False  False        False     False
 295              False             False  False        False     False

 [296 rows x 164 columns],
 [['cider',
   'meatballs',
   'eggplant',
   'oil',
   'asparagus',
   'pokemon scarlet',
   'tomatoes',
   'canned_tuna',
   'eggs',
   'salt'],
  ['soup',
   'cake',
   'spaghetti',
   'oil',
   'bacon',
   'sparkling water',
   'whole weat flour',
   'salmon',
   'eggs',
   'megaman zero 2'],
  ['soda', 'cake', 'meatballs', 'vegetables mix', 'mayonnaise', 'salt'],
  ['meatballs',
   'energy bar',
   'beer',
   'mineral water',
   'oil',
   'cereals',
   'catfish',
   'fresh bread',
   'yogurt cake',
   'vacuum cleaner'],
  ['meatballs',
   'razor',
   'mineral water',
   'oil',
   'olive oil',
   'white wine',
   'salmon',
   'spinach',
   'metroid prime',
   'mint green tea',
   'cooking oil'],
  ['mineral water',
   'eggs',
   'melons',
   'ground beef',
   'sandwich',
   'light mayo',
   'tomato juice'],
  ['soup',
   'meatballs',
   'energy bar',
   'mineral water',
   'oil',
   'portal',
   'catfish',
   'sparkling water',
   'vegetables mix',
   'tomato sauce',
   'cooking oil',
   'mushroom cream sauce'],
  ['pancakes', 'oil', 'salmon'],
  ['meatballs',
   'beer',
   'french fries',
   'seabass',
   'oil',
   'ketchup',
   'fresh bread',
   'toothpaste',
   'pasta',
   'canned_tuna',
   'salmon',
   'burgers'],
  ['pickles', 'oatmeal', 'eggplant', 'phone charger', 'honey', 'tomatoes'],
  ['cider',
   'cake',
   'meatballs',
   'mashed potato',
   'oil',
   'strawberries',
   'mayonnaise',
   'yogurt cake',
   'eggs',
   'cookies',
   'cooking oil'],
  ['meatballs',
   'oatmeal',
   'mashed potato',
   'eggplant',
   'cottage cheese',
   'frozen vegetables',
   'oil',
   'mineral water',
   'pasta',
   'eggs',
   'cooking oil',
   'cauliflower'],
  ['soda',
   'whole wheat rice',
   'meatballs',
   'french fries',
   'mineral water',
   'oil',
   'gluten free bar',
   'catfish',
   'sparkling water',
   'cream',
   'melons',
   'canned_tuna',
   'french wine',
   'salt'],
  ['french fries', 'oil', 'pasta', 'sandwich'],
  ['meatballs',
   'eggplant',
   'beer',
   'ring light',
   'mineral water',
   'seabass',
   'oil',
   'catfish'],
  ['pickles', 'oatmeal', 'oil', 'muffins', 'yogurt cake', 'cooking oil'],
  ['bramble',
   'meatballs',
   'mashed potato',
   'laptop',
   'frozen smoothie',
   'cauliflower'],
  ['mineral water', 'bacon', 'airpods', 'burger sauce', 'vegetables mix'],
  ['meatballs',
   'oatmeal',
   'grated cheese',
   'oil',
   'catfish',
   'fresh bread',
   'shrimp',
   'carrots',
   'trout',
   'canned_tuna',
   'light mayo'],
  ['soup',
   'meatballs',
   'beer',
   'mineral water',
   'oil',
   'pokemon violet',
   'catfish',
   'honey',
   'pasta',
   'ground beef',
   'sandwich',
   'burgers'],
  ['candy bars',
   'spaghetti',
   'mineral water',
   'bacon',
   'gadget for tiktok streaming',
   'pasta',
   'portal 2',
   'salmon',
   'burgers',
   'olive oil',
   'salad',
   'tomato sauce'],
  ['zucchini',
   'mineral water',
   'oil',
   'ketchup',
   'pokemon sword',
   'shrimp',
   'cream',
   'toothpaste',
   'ratchet & clank 3',
   'canned_tuna',
   'ham',
   'salmon',
   'mint green tea',
   'butter',
   'cooking oil'],
  ['mineral water', 'seabass', 'whole wheat rice', 'eggs'],
  ['cake',
   'oatmeal',
   'meatballs',
   'iPad',
   'whole wheat rice',
   'antioxydant juice',
   'oil',
   'deodorant',
   'catfish',
   'shower gel',
   'milk',
   'pasta',
   'barbecue sauce',
   'salt'],
  ['french fries',
   'turkey',
   'oil',
   'gluten free bar',
   'catfish',
   'sparkling water',
   'pasta'],
  ['soda',
   'meatballs',
   'rice',
   'mineral water',
   'seabass',
   'oil',
   'pasta',
   'minecraft',
   'cooking oil'],
  ['soup', 'oatmeal', 'seabass', 'shrimp', 'tomatoes', 'pasta'],
  ['soda',
   'meatballs',
   'rice',
   'oil',
   'pokemon scarlet',
   'mint green tea',
   'salt'],
  ['soup', 'gums', 'oil', 'eggs'],
  ['cake',
   'napkins',
   'rice',
   'turkey',
   'french fries',
   'oil',
   'shower gel',
   'gums',
   'milk',
   'ground beef',
   'cookies',
   'zucchini'],
  ['cake',
   'strong cheese',
   'turkey',
   'ketchup',
   'sparkling water',
   'final fantasy XXII',
   'cream',
   'gums',
   'parmesan cheese',
   'metroid prime',
   'herb & pepper',
   'ratchet & clank 2'],
  ['cider',
   'cake',
   'rice',
   'grated cheese',
   'frozen smoothie',
   'oil',
   'fresh bread',
   'whole weat flour',
   'yogurt cake',
   'herb & pepper',
   'chocolate bread'],
  ['candy bars',
   'black beer',
   'napkins',
   'oatmeal',
   'whole wheat rice',
   'beer',
   'ketchup',
   'oil',
   'french wine',
   'fresh bread',
   'gums',
   'carrots',
   'melons',
   'babies food',
   'eggs',
   'butter',
   'cooking oil'],
  ['soup',
   'napkins',
   'iPad',
   'pokemon violet',
   'oil',
   'ketchup',
   'muffins',
   'babies food',
   'pasta',
   'cookies'],
  ['candy bars',
   'soup',
   'cake',
   'black tea',
   'asparagus',
   'almonds',
   'blueberries',
   'fresh tuna'],
  ['candy bars',
   'oatmeal',
   'eggplant',
   'pokemon scarlet',
   'chicken',
   'cat food'],
  ['candy bars',
   'cake',
   'zucchini',
   'oil',
   'portal',
   'fresh bread',
   'gums',
   'sandwich',
   'cookies',
   'body spray',
   'butter',
   'megaman zero 4',
   'tea'],
  ['cake',
   'meatballs',
   'beer',
   'chicken',
   'oil',
   'flax seed',
   'catfish',
   'vegetables mix',
   'gums',
   'tomatoes',
   'whole weat flour',
   'water spray',
   'bluetooth headphones'],
  ['meatballs', 'rice', 'catfish', 'salmon', 'eggs', 'burgers'],
  ['meatballs', 'mineral water', 'seabass', 'oil', 'pasta', 'cooking oil'],
  ['iPad',
   'turkey',
   'mineral water',
   'catfish',
   'vegetables mix',
   'energy drink',
   'tomatoes',
   'red wine'],
  ['cider',
   'meatballs',
   'mineral water',
   'oil',
   'seabass',
   'strawberries',
   'pokemon sword',
   'parmesan cheese',
   'pasta',
   'corn',
   'canned_tuna',
   'eggs',
   'chicken'],
  ['soda',
   'whole wheat pasta',
   'cake',
   'chutney',
   'rice',
   'oil',
   'black tea',
   'vegetables mix',
   'ham',
   'salad',
   'bluetooth headphones',
   'cooking oil',
   'tea'],
  ['meatballs',
   'oatmeal',
   'strong cheese',
   'oil',
   'sparkling water',
   'melons',
   'sandwich'],
  ['candy bars',
   'soda',
   'cake',
   'meatballs',
   'soup',
   'iPad',
   'beer',
   'bacon',
   'salmon'],
  ['whole weat flour', 'portal', 'salmon', 'salt'],
  ['shampoo',
   'soda',
   'meatballs',
   'mineral water',
   'oil',
   'seabass',
   'whole weat flour',
   'canned_tuna',
   'salmon',
   'burgers'],
  ['meatballs', 'oil', 'asparagus', 'vegetables mix', 'canned_tuna'],
  ['meatballs',
   'beer',
   'mineral water',
   'bacon',
   'flax seed',
   'cream',
   'pasta',
   'yogurt cake',
   'canned_tuna',
   'sandwich',
   'zucchini',
   'salt'],
  ['soup',
   'whole wheat pasta',
   'meatballs',
   'mineral water',
   'oil',
   'strawberries',
   'bacon',
   'canned_tuna',
   'butter'],
  ['yams',
   'meatballs',
   'strong cheese',
   'mineral water',
   'seabass',
   'oil',
   'eggs',
   'portal',
   'muffins',
   'almonds',
   'salmon',
   'sandwich',
   'burgers'],
  ['meatballs',
   'mineral water',
   'cat food',
   'ketchup',
   'tomatoes',
   'portal 2',
   'tomato sauce',
   'salt'],
  ['pickles',
   'meatballs',
   'mineral water',
   'oil',
   'fromage blanc',
   'strawberries',
   'yogurt cake',
   'ham',
   'sandwich',
   'salmon',
   'red wine',
   'cooking oil'],
  ['pickles',
   'bramble',
   'meatballs',
   'pokemon violet',
   'bacon',
   'oil',
   'mineral water',
   'catfish',
   'herb & pepper',
   'salt'],
  ['meatballs',
   'mineral water',
   'oil',
   'seabass',
   'ketchup',
   'asparagus',
   'fresh bread',
   'tomatoes',
   'ham',
   'salmon'],
  ['oatmeal',
   'meatballs',
   'mineral water',
   'oil',
   'pokemon scarlet',
   'corn',
   'ham',
   'salmon',
   'ratchet & clank 3',
   'water spray'],
  ['beer',
   'mineral water',
   'oil',
   'pasta',
   'canned_tuna',
   'salmon',
   'eggs',
   'ham',
   'salt'],
  ['meatballs',
   'turkey',
   'mineral water',
   'oil',
   'pet food',
   'salmon',
   'cookies',
   'salt'],
  ['meatballs',
   'oil',
   'dog food',
   'tomatoes',
   'pasta',
   'canned_tuna',
   'sandwich',
   'light mayo',
   'cooking oil',
   'salt'],
  ['final fantasy XIX',
   'meatballs',
   'mineral water',
   'oil',
   'catfish',
   'canned_tuna'],
  ['cake',
   'meatballs',
   'mineral water',
   'oil',
   'pokemon scarlet',
   'pasta',
   'chicken'],
  ['chocolate',
   'dessert wine',
   'meatballs',
   'oil',
   'flax seed',
   'seabass',
   'shower gel',
   'salmon',
   'sandwich',
   'salt',
   'french wine',
   'tea'],
  ['yams',
   'cake',
   'meatballs',
   'ring light',
   'oil',
   'strawberries',
   'honey',
   'final fantasy XXII',
   'whole weat flour',
   'brownies',
   'salmon',
   'eggs',
   'cooking oil'],
  ['meatballs',
   'cottage cheese',
   'turkey',
   'oil',
   'catfish',
   'fresh bread',
   'canned_tuna',
   'salmon'],
  ['black beer',
   'chocolate',
   'oil',
   'white wine',
   'canned_tuna',
   'spinach',
   'green beans',
   'ground beef',
   'salad'],
  ['turkey',
   'mineral water',
   'oil',
   'bacon',
   'fromage blanc',
   'sparkling water',
   'fresh bread',
   'toothpaste',
   'trout',
   'pasta',
   'canned_tuna',
   'salmon',
   'chicken'],
  ['cake',
   'oatmeal',
   'meatballs',
   'mineral water',
   'seabass',
   'oil',
   'flax seed',
   'deodorant',
   'vegetables mix',
   'fresh bread',
   'body spray',
   'red wine'],
  ['mineral water',
   'oil',
   'chicken',
   'catfish',
   'vegetables mix',
   'fresh bread',
   'pasta',
   'almonds',
   'body spray',
   'tomato juice',
   'fresh tuna',
   'metroid fusion'],
  ['meatballs',
   'oil',
   'bacon',
   'catfish',
   'vegetables mix',
   'yogurt cake',
   'canned_tuna'],
  ['meatballs',
   'sparkling water',
   'gums',
   'parmesan cheese',
   'pasta',
   'eggs',
   'burgers'],
  ['yams', 'grated cheese', 'carrots', 'olive oil', 'body spray'],
  ['cake',
   'whole wheat rice',
   'spaghetti',
   'oatmeal',
   'ketchup',
   'seabass',
   'oil',
   'catfish',
   'fromage blanc',
   'toilet paper',
   'hand protein bar',
   'champagne',
   'pasta',
   'tomatoes',
   'eggs',
   'olive oil',
   'herb & pepper',
   'phone car charger'],
  ['soup',
   'bacon',
   'oil',
   'flax seed',
   'pet food',
   'canned_tuna',
   'salmon',
   'blueberries',
   'herb & pepper',
   'protein bar'],
  ['turkey', 'megaman zero 4', 'oil', 'mashed potato'],
  ['meatballs', 'mineral water', 'avocado', 'cereals', 'oil'],
  ['cotton buds', 'french fries', 'oil', 'pasta', 'salmon', 'salt'],
  ['pickles',
   'chocolate',
   'meatballs',
   'napkins',
   'energy bar',
   'beer',
   'mineral water',
   'oil',
   'pokemon violet',
   'dog food',
   'tomatoes',
   'pasta',
   'ham',
   'salmon',
   'eggs'],
  ['soda', 'turkey', 'mineral water', 'bacon', 'pasta', 'cat food', 'salt'],
  ['pokemon violet',
   'oil',
   'catfish',
   'whole weat flour',
   'canned_tuna',
   'chili',
   'megaman zero 4'],
  ['soda',
   'soup',
   'energy bar',
   'oil',
   'flax seed',
   'pasta',
   'salmon',
   'zucchini'],
  ['oil',
   'megaman zero 2',
   'megaman zero',
   'water spray',
   'salmon',
   'olive oil'],
  ['mineral water',
   'oil',
   'chicken',
   'honey',
   'parmesan cheese',
   'megaman zero 2'],
  ['cake',
   'meatballs',
   'mineral water',
   'oil',
   'green grapes',
   'catfish',
   'vegetables mix',
   'energy drink',
   'tomato juice',
   'butter',
   'cauliflower',
   'salt'],
  ['spaghetti',
   'grated cheese',
   'oil',
   'whole weat flour',
   'salmon',
   'red wine',
   'salt'],
  ['candy bars',
   'tooth brush',
   'cake',
   'meatballs',
   'shallot',
   'light mayo',
   'cooking oil'],
  ['oil', 'meatballs', 'eggs'],
  ['dessert wine',
   'meatballs',
   'beer',
   'mineral water',
   'oil',
   'ketchup',
   'seabass',
   'tomatoes',
   'canned_tuna',
   'olive oil',
   'mint',
   'cooking oil',
   'salt'],
  ['pickles',
   'shallot',
   'meatballs',
   'rice',
   'mashed potato',
   'ring light',
   'mineral water',
   'oil',
   'french fries',
   'eggs',
   'black tea',
   'mayonnaise',
   'pasta',
   'salmon',
   'sandwich',
   'mint'],
  ['ratchet & clank', 'vacuum cleaner', 'oil', 'meatballs'],
  ['meatballs',
   'french fries',
   'frozen vegetables',
   'oil',
   'seabass',
   'catfish',
   'mayonnaise',
   'nonfat milk',
   'minecraft',
   'ham',
   'sandwich',
   'eggs',
   'green beans',
   'ground beef'],
  ['zucchini',
   'french fries',
   'oil',
   'pasta',
   'spinach',
   'phone car charger',
   'salt'],
  ['cake',
   'meatballs',
   'beer',
   'mineral water',
   'oil',
   'cream',
   'pasta',
   'muffins',
   'canned_tuna',
   'ground beef',
   'metroid fusion'],
  ['megaman zero 3', 'pasta', 'canned_tuna', 'beer'],
  ['meatballs',
   'oil',
   'bacon',
   'fromage blanc',
   'pokemon sword',
   'pasta',
   'muffins',
   'canned_tuna',
   'salmon',
   'salad'],
  ['cottage cheese',
   'mashed potato',
   'oil',
   'pasta',
   'ham',
   'canned_tuna',
   'salmon',
   'burgers',
   'ground beef'],
  ['meatballs',
   'antioxydant juice',
   'oil',
   'fresh bread',
   'champagne',
   'tomatoes',
   'canned_tuna',
   'burgers'],
  ['meatballs',
   'rice',
   'cream',
   'yogurt cake',
   'salmon',
   'cooking oil',
   'salt'],
  ['whole wheat rice',
   'mineral water',
   'oil',
   'ketchup',
   'hand protein bar',
   'portal 2',
   'phone car charger',
   'mint green tea',
   'fresh tuna'],
  ['soup', 'meatballs', 'bacon', 'oil', 'pasta', 'salmon', 'olive oil'],
  ['meatballs',
   'spaghetti',
   'energy bar',
   'rice',
   'mineral water',
   'seabass',
   'oil',
   'flax seed',
   'catfish',
   'vegetables mix',
   'almonds',
   'extra dark chocolate',
   'chicken'],
  ['cake', 'meatballs', 'beer', 'mineral water', 'oil', 'fresh bread', 'ham'],
  ['chocolate',
   'soup',
   'meatballs',
   'energy bar',
   'oil',
   'seabass',
   'milk',
   'pasta',
   'green beans',
   'salt'],
  ['shampoo',
   'meatballs',
   'mineral water',
   'oil',
   'vegetables mix',
   'escalope',
   'canned_tuna',
   'half-life 2',
   'cologne'],
  ['dessert wine',
   'meatballs',
   'pokemon violet',
   'oil',
   'french wine',
   'asparagus',
   'low fat yogurt',
   'melons',
   'ground beef',
   'ratchet & clank 2'],
  ['meatballs',
   'mineral water',
   'sparkling water',
   'mayonnaise',
   'canned_tuna',
   'salmon',
   'cookies',
   'red wine',
   'french wine'],
  ['phone charger',
   'catfish',
   'red wine',
   'pasta',
   'yogurt cake',
   'green beans',
   'tomato juice',
   'cooking oil'],
  ['meatballs',
   'whole wheat rice',
   'antioxydant juice',
   'laptop',
   'mineral water',
   'seabass',
   'french fries',
   'energy drink',
   'canned_tuna',
   'salmon',
   'butter'],
  ['shallot',
   'meatballs',
   'spaghetti',
   'mineral water',
   'oil',
   'seabass',
   'catfish',
   'tomatoes',
   'pasta',
   'brownies',
   'canned_tuna',
   'half-life 2',
   'body spray',
   'green grapes'],
  ['soup',
   'french fries',
   'oil',
   'catfish',
   'pasta',
   'escalope',
   'salmon',
   'cologne',
   'chicken',
   'herb & pepper',
   'cooking oil'],
  ['meatballs',
   'oatmeal',
   'mineral water',
   'oil',
   'avocado',
   'bacon',
   'catfish',
   'flax seed',
   'pasta',
   'yogurt cake',
   'fresh tuna'],
  ['dessert wine',
   'meatballs',
   'iMac',
   'oil',
   'dog food',
   'vegetables mix',
   'pasta',
   'escalope',
   'phone car charger',
   'chicken'],
  ['yams',
   'meatballs',
   'cottage cheese',
   'turkey',
   'mineral water',
   'oil',
   'seabass',
   'ham',
   'green grapes',
   'salt'],
  ['cake',
   'mineral water',
   'oil',
   'portal',
   'honey',
   'sparkling water',
   'pokemon scarlet',
   'shrimp',
   'tomatoes',
   'pasta',
   'salmon',
   'burgers',
   'megaman zero 4',
   'cooking oil'],
  ['whole wheat rice',
   'meatballs',
   'rice',
   'beer',
   'oil',
   'cream',
   'pasta',
   'body spray',
   'toilet paper',
   'ratchet & clank 2'],
  ['cider', 'mineral water', 'oil', 'canned_tuna'],
  ['cottage cheese',
   'beer',
   'french fries',
   'mineral water',
   'oil',
   'flax seed',
   'gums',
   'energy drink',
   'pasta',
   'almonds',
   'muffins',
   'eggs',
   'razor'],
  ['whole wheat rice',
   'oil',
   'burger sauce',
   'fresh bread',
   'salmon',
   'spinach',
   'burgers',
   'chicken',
   'butter'],
  ['candy bars',
   'meatballs',
   'oil',
   'bacon',
   'blueberries',
   'salmon',
   'white wine',
   'light mayo'],
  ['beer',
   'oil',
   'whole weat flour',
   'tomatoes',
   'blueberries',
   'salmon',
   'mint'],

In [78]:
frequent_itemsets, rules = apriori_algorithm(df_items0, min_support=0.2, metric='confidence', confidence_threshold = 0.2)

In [79]:
rules.sort_values('lift', ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
13,"(mineral water, oil)",(meatballs),0.354730,0.537162,0.239865,0.676190,1.258820,1.0,0.049317,1.429352,0.318634,0.367876,0.300382,0.561366
16,(meatballs),"(mineral water, oil)",0.537162,0.354730,0.239865,0.446541,1.258820,1.0,0.049317,1.165886,0.444227,0.367876,0.142283,0.561366
15,(mineral water),"(meatballs, oil)",0.449324,0.456081,0.239865,0.533835,1.170482,1.0,0.034937,1.166794,0.264495,0.360406,0.142951,0.529880
14,"(meatballs, oil)",(mineral water),0.456081,0.449324,0.239865,0.525926,1.170482,1.0,0.034937,1.161582,0.267781,0.360406,0.139105,0.529880
2,(mineral water),(meatballs),0.449324,0.537162,0.277027,0.616541,1.147775,1.0,0.035667,1.207008,0.233802,0.390476,0.171505,0.566132
3,(meatballs),(mineral water),0.537162,0.449324,0.277027,0.515723,1.147775,1.0,0.035667,1.137110,0.278173,0.390476,0.120577,0.566132
17,(oil),"(mineral water, meatballs)",0.793919,0.277027,0.239865,0.302128,1.090607,1.0,0.019928,1.035967,0.403140,0.288618,0.034719,0.583991
12,"(mineral water, meatballs)",(oil),0.277027,0.793919,0.239865,0.865854,1.090607,1.0,0.019928,1.536241,0.114914,0.288618,0.349060,0.583991
10,(salmon),(oil),0.280405,0.793919,0.239865,0.855422,1.077467,1.0,0.017246,1.425394,0.099914,0.287449,0.298440,0.578775
11,(oil),(salmon),0.793919,0.280405,0.239865,0.302128,1.077467,1.0,0.017246,1.031126,0.348880,0.287449,0.030187,0.578775
4,(meatballs),(oil),0.537162,0.793919,0.456081,0.849057,1.069450,1.0,0.029618,1.365287,0.140308,0.521236,0.267553,0.711762
5,(oil),(meatballs),0.793919,0.537162,0.456081,0.574468,1.069450,1.0,0.029618,1.087669,0.315118,0.521236,0.080603,0.711762
1,(oil),(canned_tuna),0.793919,0.290541,0.246622,0.310638,1.069174,1.0,0.015956,1.029154,0.313946,0.294355,0.028328,0.579738
0,(canned_tuna),(oil),0.290541,0.793919,0.246622,0.848837,1.069174,1.0,0.015956,1.363306,0.091194,0.294355,0.266489,0.579738
8,(pasta),(oil),0.320946,0.793919,0.266892,0.831579,1.047436,1.0,0.012087,1.223606,0.066692,0.314741,0.182744,0.583875
9,(oil),(pasta),0.793919,0.320946,0.266892,0.336170,1.047436,1.0,0.012087,1.022934,0.219755,0.314741,0.022420,0.583875
7,(oil),(mineral water),0.793919,0.449324,0.354730,0.446809,0.994401,1.0,-0.001997,0.995452,-0.026596,0.399240,-0.004569,0.618141
6,(mineral water),(oil),0.449324,0.793919,0.354730,0.789474,0.994401,1.0,-0.001997,0.978885,-0.010121,0.399240,-0.021570,0.618141

Assosiation Rules

Cluster 0:
- If a customer buys salt and canned tuna, they are likely to also buy tomatoes. 
- Confidence: 46.15% of those who bought salt & tuna also bought tomatoes.
- 
Cluster 1:
-

## Eclat Algorithm

In [39]:
items_list2

[['soup',
  'shallot',
  'cake',
  'fresh bread',
  'cream',
  'carrots',
  'babies food',
  'ham',
  'cookies',
  'salad',
  'tomato sauce',
  'cooking oil',
  'tea'],
 ['candy bars', 'soup', 'napkins', 'rice', 'oil', 'tea'],
 ['zucchini',
  'grated cheese',
  'ketchup',
  'oil',
  'pokemon scarlet',
  'milk',
  'water spray',
  'chicken',
  'cooking oil',
  'tea'],
 ['candy bars',
  'napkins',
  'frozen smoothie',
  'oil',
  'ham',
  'phone car charger',
  'cologne',
  'iMac',
  'tea'],
 ['cake', 'cream', 'corn', 'blueberries', 'burgers'],
 ['oil', 'babies food', 'cooking oil'],
 ['soup', 'protein bar', 'oil', 'toothpaste', 'ham', 'cooking oil', 'tea'],
 ['candy bars',
  'cake',
  'whole wheat rice',
  'oil',
  'portal',
  'black tea',
  'fresh bread',
  'ham',
  'green beans',
  'cooking oil'],
 ['meatballs',
  'cottage cheese',
  'french fries',
  'turkey',
  'oil',
  'chocolate bread',
  'tomatoes',
  'cologne',
  'cooking oil',
  'tea'],
 ['soup',
  'cooking oil',
  'cereals',
  'oil',
  'dog food',
  'deodorant',
  'tomatoes',
  'yogurt cake',
  'pet food',
  'salmon',
  'olive oil',
  'fresh tuna',
  'tea'],
 ['oil', 'pasta', 'blueberries', 'olive oil', 'mint', 'tomato juice', 'tea'],
 ['whole wheat rice',
  'meatballs',
  'frozen smoothie',
  'oil',
  'ketchup',
  'gums',
  'toothpaste',
  'cooking oil',
  'green grapes',
  'tea'],
 ['cake',
  'napkins',
  'phone charger',
  'french fries',
  'oil',
  'ketchup',
  'shower gel',
  'gums',
  'whole weat flour',
  'muffins',
  'pepper',
  'burgers',
  'bluetooth headphones',
  'cooking oil'],
 ['soup',
  'napkins',
  'oatmeal',
  'french fries',
  'gadget for tiktok streaming',
  'gums',
  'cooking oil',
  'mushroom cream sauce',
  'tea'],
 ['soup',
  'megaman zero 3',
  'french fries',
  'turkey',
  'oil',
  'ketchup',
  'gums',
  'milk',
  'babies food',
  'toilet paper',
  'salt',
  'tea'],
 ['cream', 'cereals', 'rice', 'napkins'],
 ['soup', 'oatmeal', 'oil', 'green beans', 'metroid fusion', 'tea'],
 ['candy bars',
  'cake',
  'strong cheese',
  'cereals',
  'oil',
  'final fantasy XXII',
  'fresh bread',
  'cooking oil',
  'tea'],
 ['candy bars',
  'megaman zero 3',
  'grated cheese',
  'oil',
  'fresh bread',
  'pokemon scarlet',
  'babies food',
  'salmon',
  'toilet paper',
  'cooking oil'],
 ['ketchup', 'yogurt cake', 'cooking oil', 'oil'],
 ['shampoo',
  'soup',
  'shallot',
  'napkins',
  'oil',
  'gadget for tiktok streaming',
  'toothpaste',
  'half-life 2',
  'cooking oil'],
 ['oatmeal', 'frozen vegetables', 'oil', 'sandwich', 'cooking oil'],
 ['candy bars',
  'napkins',
  'rice',
  'pokemon shield',
  'oil',
  'ketchup',
  'asparagus',
  'shower gel',
  'milk',
  'parmesan cheese',
  'escalope',
  'cooking oil',
  'tea'],
 ['burgers',
  'napkins',
  'turkey',
  'pokemon shield',
  'oil',
  'dog food',
  'shower gel',
  'muffins',
  'corn',
  'ground beef',
  'cologne',
  'cooking oil',
  'tea'],
 ['candy bars',
  'napkins',
  'spaghetti',
  'mashed potato',
  'strong cheese',
  'frozen vegetables',
  'oil',
  'avocado',
  'gums',
  'babies food',
  'tomato sauce'],
 ['candy bars',
  'pickles',
  'final fantasy XIX',
  'chocolate',
  'soda',
  'cottage cheese',
  'cereals',
  'oil',
  'honey',
  'gums',
  'cream',
  'cookies',
  'olive oil',
  'cooking oil',
  'tea'],
 ['whole wheat pasta',
  'napkins',
  'oil',
  'megaman zero 2',
  'minecraft',
  'toilet paper',
  'cooking oil',
  'tea'],
 ['protein bar',
  'whole wheat rice',
  'oatmeal',
  'hot dogs',
  'oil',
  'shower gel',
  'milk',
  'burgers',
  'tomato sauce',
  'cooking oil',
  'green grapes'],
 ['soup',
  'cake',
  'oatmeal',
  'grated cheese',
  'oil',
  'cream',
  'muffins',
  'pet food',
  'eggs',
  'tea'],
 ['candy bars',
  'tooth brush',
  'cake',
  'cottage cheese',
  'grated cheese',
  'strong cheese',
  'oil',
  'portal',
  'fresh bread',
  'whole weat flour',
  'parmesan cheese',
  'eggs'],
 ['cereals', 'whole wheat rice', 'iPad', 'tea'],
 ['burgers',
  'candy bars',
  'cake',
  'soup',
  'mashed potato',
  'ring light',
  'olive oil',
  'ketchup',
  'gluten free bar',
  'pet food',
  'babies food',
  'chili',
  'cologne',
  'toilet paper',
  'cooking oil',
  'tea'],
 ['cake',
  'energy bar',
  'flax seed',
  'sparkling water',
  'honey',
  'gums',
  'muffins',
  'babies food',
  'melons',
  'butter',
  'cooking oil',
  'tea'],
 ['candy bars',
  'napkins',
  'cooking oil',
  'oil',
  'fresh bread',
  'gums',
  'pasta',
  'muffins',
  'chicken',
  'body spray'],
 ['tooth brush',
  'cotton buds',
  'turkey',
  'oil',
  'mayonnaise',
  'extra dark chocolate',
  'toilet paper',
  'cooking oil'],
 ['soup',
  'mashed potato',
  'strong cheese',
  'oil',
  'deodorant',
  'half-life 2',
  'olive oil',
  'cooking oil',
  'tea'],
 ['cake',
  'cottage cheese',
  'french fries',
  'ring light',
  'vegetables mix',
  'shrimp',
  'milk',
  'spinach'],
 ['candy bars',
  'napkins',
  'turkey',
  'oil',
  'strawberries',
  'ketchup',
  'burger sauce',
  'final fantasy XXII',
  'fresh bread',
  'pet food',
  'escalope',
  'ratchet & clank 3',
  'tea'],
 ['meatballs', 'beer', 'oil', 'olive oil', 'zucchini'],
 ['soup',
  'tooth brush',
  'napkins',
  'french fries',
  'turkey',
  'oil',
  'pokemon shield',
  'strawberries',
  'asparagus',
  'mayonnaise',
  'gums',
  'pasta',
  'escalope',
  'eggs',
  'burgers',
  'mint',
  'cooking oil',
  'tea'],
 ['candy bars',
  'cake',
  'rice',
  'strong cheese',
  'pokemon violet',
  'oil',
  'milk',
  'escalope',
  'tomato sauce',
  'cooking oil',
  'tea'],
 ['candy bars',
  'soup',
  'whole wheat rice',
  'oil',
  'flax seed',
  'ratchet & clank',
  'milk',
  'cream',
  'gums',
  'pet food',
  'mayonnaise',
  'yogurt cake',
  'tea'],
 ['candy bars', 'cake', 'oatmeal', 'hot dogs', 'french fries', 'butter'],
 ['cake',
  'phone charger',
  'strong cheese',
  'oil',
  'asparagus',
  'gums',
  'muffins',
  'ham',
  'green grapes'],
 ['cake', 'french fries', 'oil', 'muffins', 'sandwich', 'cooking oil', 'tea'],
 ['whole weat flour', 'muffins', 'corn', 'butter'],
 ['tooth brush',
  'shallot',
  'mashed potato',
  'cottage cheese',
  'french fries',
  'strong cheese',
  'oil',
  'gums',
  'yogurt cake',
  'megaman zero'],
 ['cake',
  'cologne',
  'grated cheese',
  'gums',
  'metroid prime',
  'sandwich',
  'light mayo',
  'cooking oil',
  'tea'],
 ['pickles',
  'cottage cheese',
  'french fries',
  'oil',
  'ketchup',
  'gums',
  'sandwich',
  'burgers',
  'tea'],
 ['yams',
  'strong cheese',
  'cereals',
  'oil',
  'tomatoes',
  'cologne',
  'body spray',
  'butter',
  'cooking oil',
  'cauliflower',
  'tea'],
 ['cottage cheese',
  'oil',
  'catfish',
  'megaman zero 4',
  'barbecue sauce',
  'cooking oil',
  'tea'],
 ['cake',
  'oatmeal',
  'megaman zero 3',
  'oil',
  'parmesan cheese',
  'muffins',
  'cookies',
  'cooking oil',
  'tea'],
 ['pickles',
  'soup',
  'cake',
  'french fries',
  'oil',
  'deodorant',
  'shower gel',
  'muffins',
  'sandwich',
  'cat food',
  'cooking oil',
  'cauliflower',
  'tea'],
 ['yams',
  'cake',
  'napkins',
  'rice',
  'french fries',
  'fromage blanc',
  'gums',
  'mayonnaise',
  'pet food',
  'salad',
  'cooking oil'],
 ['cake',
  'spaghetti',
  'rice',
  'muffins',
  'babies food',
  'yogurt cake',
  'body spray',
  'tomato sauce',
  'cooking oil'],
 ['soup',
  'meatballs',
  'spaghetti',
  'rice',
  'oatmeal',
  'oil',
  'toothpaste',
  'milk',
  'muffins',
  'cooking oil',
  'tea'],
 ['candy bars',
  'cake',
  'eggplant',
  'french fries',
  'cereals',
  'oil',
  'frozen smoothie',
  'asparagus',
  'pokemon scarlet',
  'butter',
  'cooking oil',
  'tea'],
 ['cake',
  'whole wheat pasta',
  'oil',
  'fresh bread',
  'whole weat flour',
  'carrots',
  'light mayo',
  'tomato juice',
  'tomato sauce'],
 ['ketchup', 'oil', 'pasta', 'muffins', 'green beans', 'tea'],
 ['napkins',
  'eggplant',
  'oil',
  'fresh bread',
  'parmesan cheese',
  'muffins',
  'salmon',
  'tea'],
 ['cake',
  'french fries',
  'fresh bread',
  'sandwich',
  'toilet paper',
  'butter',
  'tea'],
 ['bramble',
  'soup',
  'cake',
  'napkins',
  'oil',
  'gadget for tiktok streaming',
  'fresh bread',
  'tomatoes',
  'canned_tuna',
  'blueberries',
  'mint',
  'butter',
  'cooking oil',
  'tea'],
 ['cake',
  'spaghetti',
  'french fries',
  'oil',
  'fresh bread',
  'gums',
  'pet food',
  'half-life: alyx',
  'cooking oil',
  'tea'],
 ['candy bars',
  'napkins',
  'meatballs',
  'ring light',
  'oil',
  'pancakes',
  'nonfat milk',
  'chili',
  'cookies',
  'protein bar'],
 ['candy bars', 'napkins', 'sparkling water', 'muffins', 'cooking oil'],
 ['burgers',
  'cake',
  'cereals',
  'oil',
  'cookies',
  'body spray',
  'salad',
  'barbecue sauce',
  'cooking oil'],
 ['candy bars',
  'cake',
  'french fries',
  'mineral water',
  'oil',
  'asparagus',
  'low fat yogurt',
  'fresh bread',
  'shrimp',
  'gums',
  'cream',
  'pet food',
  'portal 2',
  'cooking oil',
  'metroid fusion'],
 ['cake', 'whole wheat rice', 'muffins', 'cooking oil', 'tea'],
 ['soup',
  'cake',
  'oatmeal',
  'grated cheese',
  'french fries',
  'half-life 2',
  'eggs',
  'tea'],
 ['soup',
  'cake',
  'oatmeal',
  'oil',
  'deodorant',
  'low fat yogurt',
  'muffins',
  'pet food',
  'almonds',
  'cologne',
  'megaman zero',
  'cooking oil',
  'tea'],
 ['soup',
  'cake',
  'oil',
  'airpods',
  'black tea',
  'final fantasy XXII',
  'babies food',
  'white wine',
  'burgers',
  'salt',
  'cooking oil',
  'cauliflower',
  'tea'],
 ['yams', 'oil', 'pasta', 'cooking oil', 'green grapes'],
 ['cotton buds',
  'napkins',
  'zucchini',
  'strong cheese',
  'oil',
  'strawberries',
  'parmesan cheese',
  'muffins',
  'whole weat flour',
  'phone car charger',
  'olive oil',
  'salad',
  'body spray',
  'vacuum cleaner',
  'tea'],
 ['candy bars',
  'tooth brush',
  'cake',
  'strong cheese',
  'mineral water',
  'oil',
  'pokemon sword',
  'mayonnaise',
  'tea'],
 ['frozen smoothie',
  'oil',
  'fromage blanc',
  'burger sauce',
  'vegetables mix',
  'fresh bread',
  'cookies',
  'butter'],
 ['candy bars',
  'soup',
  'napkins',
  'french fries',
  'oil',
  'shower gel',
  'gums',
  'melons',
  'yogurt cake',
  'blueberries',
  'eggs',
  'olive oil'],
 ['cider',
  'soup',
  'dessert wine',
  'cake',
  'soda',
  'shampoo',
  'oil',
  'flax seed',
  'toothpaste',
  'whole weat flour',
  'cream',
  'final fantasy XX',
  'chicken',
  'metroid fusion',
  'tea'],
 ['candy bars',
  'soup',
  'rice',
  'ratchet & clank',
  'gums',
  'cooking oil',
  'tea'],
 ['candy bars',
  'meatballs',
  'turkey',
  'oil',
  'bacon',
  'pokemon scarlet',
  'gums',
  'cookies',
  'tomato juice',
  'barbecue sauce',
  'cooking oil',
  'tea'],
 ['cake',
  'spaghetti',
  'strong cheese',
  'oil',
  'green beans',
  'asparagus',
  'gums',
  'whole weat flour',
  'muffins',
  'cookies',
  'olive oil',
  'cooking oil',
  'tea'],
 ['yams',
  'shower gel',
  'vegetables mix',
  'salmon',
  'mushroom cream sauce',
  'tea'],
 ['tooth brush', 'whole wheat rice', 'oil', 'fresh bread', 'gums', 'tea'],
 ['soup', 'cake', 'soda', 'oil', 'airpods', 'half-life 2', 'portal 2'],
 ['soup', 'oil', 'cereals', 'tea'],
 ['candy bars',
  'cake',
  'airpods',
  'ketchup',
  'oil',
  'light mayo',
  'cooking oil',
  'tea'],
 ['candy bars', 'shower gel', 'tea'],
 ['candy bars',
  'soup',
  'cake',
  'zucchini',
  'rice',
  'french fries',
  'strong cheese',
  'ketchup',
  'laptop',
  'fresh bread',
  'toothpaste',
  'pet food',
  'cookies',
  'megaman zero 4',
  'cooking oil',
  'tea'],
 ['cake',
  'shallot',
  'spaghetti',
  'frozen smoothie',
  'oil',
  'strawberries',
  'ketchup',
  'final fantasy XXII',
  'shrimp',
  'cologne',
  'cooking oil'],
 ['candy bars',
  'bramble',
  'mineral water',
  'shower gel',
  'toothpaste',
  'cream',
  'extra dark chocolate',
  'eggs',
  'cooking oil'],
 ['soda',
  'chutney',
  'oatmeal',
  'strong cheese',
  'french fries',
  'oil',
  'strawberries',
  'shower gel',
  'final fantasy XXII',
  'gums',
  'whole weat flour',
  'almonds',
  'blueberries',
  'spinach',
  'tomato sauce',
  'cooking oil',
  'tea'],
 ['candy bars', 'bacon', 'oil', 'gums', 'yogurt cake', 'cooking oil'],
 ['candy bars', 'grated cheese', 'fromage blanc', 'gums', 'green tea'],
 ['energy bar',
  'mineral water',
  'seabass',
  'oil',
  'melons',
  'cookies',
  'metroid fusion'],
 ['soda', 'oil', 'fresh bread', 'gums', 'cologne', 'cooking oil'],
 ['fresh bread', 'gums', 'pokemon scarlet', 'tea'],
 ['oil',
  'ketchup',
  'airpods',
  'sparkling water',
  'gums',
  'cream',
  'yogurt cake',
  'body spray',
  'cooking oil'],
 ['candy bars',
  'cologne',
  'laptop',
  'oil',
  'low fat yogurt',
  'fresh bread',
  'gums',
  'mayonnaise',
  'white wine',
  'cookies',
  'cooking oil',
  'tea'],
 ['cake',
  'napkins',
  'strong cheese',
  'french fries',
  'oil',
  'avocado',
  'gums',
  'tomatoes',
  'mayonnaise',
  'metroid fusion',
  'cookies',
  'cooking oil',
  'mushroom cream sauce',
  'tea'],
 ['candy bars',
  'cake',
  'napkins',
  'cologne',
  'gums',
  'muffins',
  'yogurt cake',
  'ratchet & clank 3',
  'burgers',
  'megaman zero 4',
  'cooking oil'],
 ['french fries',
  'oil',
  'fresh bread',
  'muffins',
  'yogurt cake',
  'white wine',
  'cologne',
  'megaman zero 4',
  'butter',
  'tea'],
 ['candy bars',
  'cake',
  'oil',
  'ratchet & clank',
  'gums',
  'escalope',
  'half-life: alyx',
  'tomato sauce',
  'cooking oil',
  'tea'],
 ['cereals',
  'ketchup',
  'low fat yogurt',
  'parmesan cheese',
  'pet food',
  'sandwich',
  'cookies',
  'tea'],
 ['candy bars',
  'soup',
  'tooth brush',
  'oatmeal',
  'turkey',
  'fresh bread',
  'toothpaste',
  'milk',
  'muffins',
  'sandwich',
  'toilet paper',
  'salad',
  'cooking oil'],
 ['soup',
  'oatmeal',
  'oil',
  'pasta',
  'cookies',
  'megaman zero 4',
  'red wine',
  'cooking oil',
  'tea'],
 ['chocolate', 'cream', 'trout', 'iMac', 'zucchini'],
 ['cake', 'oil', 'portal', 'yogurt cake', 'pet food'],
 ['soup',
  'cake',
  'napkins',
  'spaghetti',
  'strong cheese',
  'french fries',
  'gadget for tiktok streaming',
  'cereals',
  'final fantasy XXII',
  'extra dark chocolate',
  'olive oil',
  'mint',
  'tea'],
 ['fresh bread', 'napkins', 'tomato sauce', 'tea'],
 ['candy bars',
  'soda',
  'bramble',
  'cottage cheese',
  'turkey',
  'oil',
  'gadget for tiktok streaming',
  'milk',
  'muffins',
  'pet food',
  'cooking oil',
  'tea'],
 ['candy bars', 'cake', 'laptop', 'frozen smoothie', 'fresh bread', 'milk'],
 ['candy bars', 'oil', 'gluten free bar', 'cooking oil', 'cauliflower', 'tea'],
 ['soup', 'napkins', 'oil', 'muffins', 'pasta', 'olive oil', 'barbecue sauce'],
 ['oatmeal',
  'oil',
  'shower gel',
  'pokemon scarlet',
  'milk',
  'hand protein bar',
  'escalope',
  'barbecue sauce',
  'chocolate bread'],
 ['candy bars',
  'cake',
  'oil',
  'shower gel',
  'cream',
  'pasta',
  'green beans',
  'iMac',
  'cooking oil',
  'tea'],
 ['candy bars',
  'cake',
  'oil',
  'fromage blanc',
  'fresh bread',
  'minecraft',
  'babies food',
  'cooking oil'],
 ['final fantasy XIX',
  'soda',
  'cake',
  'mashed potato',
  'oil',
  'bacon',
  'flax seed',
  'cream',
  'babies food',
  'pet food',
  'chili',
  'olive oil',
  'tea'],
 ['cake',
  'spaghetti',
  'mashed potato',
  'oil',
  'milk',
  'burgers',
  'toilet paper',
  'cat food'],
 ['soup',
  'oatmeal',
  'iPad',
  'cottage cheese',
  'oil',
  'toothpaste',
  'cream',
  'gums',
  'olive oil',
  'red wine',
  'tea'],
 ['final fantasy XIX', 'cotton buds', 'napkins', 'chutney', 'tea'],
 ['shampoo',
  'final fantasy XIX',
  'yams',
  'oatmeal',
  'french fries',
  'oil',
  'flax seed',
  'mayonnaise',
  'red wine',
  'herb & pepper'],
 ['energy bar',
  'oil',
  'airpods',
  'strawberries',
  'gums',
  'energy drink',
  'tomato sauce',
  'cooking oil',
  'tea'],
 ['final fantasy XIX',
  'shallot',
  'mashed potato',
  'frozen vegetables',
  'oil',
  'water spray',
  'iMac'],
 ['oatmeal',
  'rice',
  'ring light',
  'cereals',
  'oil',
  'asparagus',
  'shower gel',
  'ratchet & clank',
  'metroid prime',
  'final fantasy XX',
  'body spray',
  'cooking oil',
  'tea'],
 ['cider',
  'soup',
  'barbecue sauce',
  'ketchup',
  'avocado',
  'shower gel',
  'gums',
  'salad',
  'tomato sauce',
  'cooking oil',
  'tea'],
 ['cake',
  'whole wheat rice',
  'napkins',
  'grated cheese',
  'oil',
  'fromage blanc',
  'white wine',
  'eggs',
  'cooking oil'],
 ['oil',
  'fromage blanc',
  'fresh bread',
  'toothpaste',
  'pancakes',
  'pasta',
  'final fantasy XX',
  'half-life: alyx',
  'tea'],
 ['dessert wine',
  'cake',
  'napkins',
  'oil',
  'extra dark chocolate',
  'cooking oil',
  'tea'],
 ['oil',
  'ketchup',
  'gums',
  'parmesan cheese',
  'hand protein bar',
  'olive oil',
  'tomato sauce'],
 ['soup', 'cake', 'napkins', 'oil', 'sparkling water', 'olive oil', 'tea'],
 ['yams',
  'black beer',
  'cake',
  'french fries',
  'dog food',
  'milk',
  'muffins',
  'cooking oil',
  'tea'],
 ['soup',
  'cottage cheese',
  'mineral water',
  'oil',
  'frozen vegetables',
  'final fantasy XXII',
  'ratchet & clank',
  'gums',
  'tomatoes',
  'yogurt cake',
  'cooking oil',
  'tea'],
 ['napkins',
  'oil',
  'fromage blanc',
  'asparagus',
  'vegetables mix',
  'gums',
  'muffins',
  'pasta',
  'half-life 2',
  'cooking oil',
  'tea'],
 ['light cream',
  'napkins',
  'french fries',
  'muffins',
  'cookies',
  'body spray',
  'cooking oil'],
 ['yams', 'oil', 'white wine', 'water spray', 'green grapes'],
 ['cake',
  'napkins',
  'cotton buds',
  'french fries',
  'frozen vegetables',
  'oil',
  'catfish',
  'fresh bread',
  'ratchet & clank',
  'pet food',
  'yogurt cake',
  'phone car charger',
  'cooking oil',
  'tea'],
 ['gluten free bar',
  'shower gel',
  'ratchet & clank',
  'parmesan cheese',
  'babies food',
  'white wine',
  'cooking oil',
  'tea'],
 ['iphone 10',
  'hot dogs',
  'pokemon shield',
  'toothpaste',
  'carrots',
  'muffins',
  'tomatoes',
  'cookies',
  'cooking oil',
  'tea'],
 ['black beer',
  'tooth brush',
  'whole wheat pasta',
  'whole wheat rice',
  'samsung galaxy 10',
  'strong cheese',
  'oil',
  'flax seed',
  'burger sauce',
  'fresh bread',
  'gums',
  'herb & pepper',
  'cooking oil',
  'tea'],
 ['candy bars',
  'whole wheat pasta',
  'oatmeal',
  'barbecue sauce',
  'asparagus',
  'herb & pepper',
  'cooking oil',
  'cauliflower'],
 ['cake', 'cottage cheese', 'oil', 'cream', 'mint green tea', 'tea'],
 ['oil', 'flax seed', 'fresh bread', 'cream', 'cooking oil'],
 ['shampoo',
  'bramble',
  'napkins',
  'mint green tea',
  'strong cheese',
  'oil',
  'bacon',
  'deodorant',
  'fresh bread',
  'gums',
  'muffins',
  'olive oil',
  'butter',
  'cooking oil',
  'tea'],
 ['cake',
  'napkins',
  'spaghetti',
  'oil',
  'milk',
  'muffins',
  'almonds',
  'olive oil',
  'tea'],
 ['candy bars',
  'dessert wine',
  'rice',
  'french fries',
  'minecraft',
  'olive oil',
  'tea'],
 ['soda', 'grated cheese', 'oil', 'mayonnaise', 'yogurt cake'],
 ['cake',
  'megaman zero 3',
  'dog food',
  'sparkling water',
  'final fantasy XXII',
  'fresh tuna',
  'chocolate bread'],
 ['soup',
  'spaghetti',
  'phone charger',
  'french fries',
  'oil',
  'seabass',
  'babies food',
  'corn',
  'half-life: alyx',
  'green beans',
  'cooking oil',
  'tea'],
 ['bramble',
  'oil',
  'tomatoes',
  'muffins',
  'babies food',
  'parmesan cheese',
  'tea'],
 ['pickles', 'oil', 'ham', 'cooking oil'],
 ['oatmeal',
  'cotton buds',
  'oil',
  'ketchup',
  'ratchet & clank',
  'gums',
  'tomatoes',
  'babies food',
  'ratchet & clank 3',
  'body spray',
  'tea'],
 ['candy bars',
  'cake',
  'oatmeal',
  'light cream',
  'oil',
  'airpods',
  'fresh bread',
  'gums',
  'pasta',
  'babies food',
  'melons',
  'cookies',
  'olive oil',
  'cooking oil',
  'tea'],
 ['soup',
  'cake',
  'meatballs',
  'antioxydant juice',
  'spaghetti',
  'french fries',
  'oil',
  'flax seed',
  'gums',
  'pet food',
  'yogurt cake',
  'escalope',
  'olive oil',
  'salad',
  'french wine'],

In [40]:
eclat_algorithm(items_list2, min_combination = 2, max_combination = 2, min_support = 0.02)

Combination 2 by 2

6786it [01:14, 91.36it/s]

                            support
oil & cooking oil          0.428647
tea & oil                  0.426828
cake & oil                 0.329480
tea & cooking oil          0.304542
candy bars & oil           0.261237
...                             ...
napkins & rice             0.020185
shallot & oil              0.020185
tea & deodorant            0.020185
babies food & fresh bread  0.020127
olive oil & ketchup        0.020127

[306 rows x 1 columns]