# **CLUSTERING NOTEBOOK**

## Libraries

In [162]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from umap.umap_ import UMAP
from sklearn.metrics import silhouette_samples, silhouette_score
import matplotlib.cm as cm
from sklearn.decomposition import PCA
import plotly.express as px
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [163]:
import sys
import os

# Get the absolute path of the source_code folder
source_code_path = os.path.abspath('../source_code')

# Add the source_code folder to sys.path
if source_code_path not in sys.path:
    sys.path.append(source_code_path)

from utils import *
from preprocessing import *
from clustering import *
from analysis import *

# Get the absolute path of the source_code folder
clustering_outputs_path = os.path.abspath('../clustering_outputs')

# Add the source_code folder to sys.path
if clustering_outputs_path not in sys.path:
    sys.path.append(clustering_outputs_path)

## Load Data

In [164]:
customer_info = load_dataset('../customer_info.csv')

In [165]:
#customer_info.columns

In [166]:
# Calling the clusters
hierarchical8_notscaled=load_dataset('../clustering_outputs/hierarchical8_notscaled.csv')
hierarchical8_scaled=load_dataset('../clustering_outputs/hierarchical8_scaled.csv')

In [275]:
customer_basket = load_dataset('../customer_basket.csv')

## Analysis

In [7]:
vars, cluster_avg, database_avg=compute_average_multi(hierarchical8_scaled, 'cluster')

In [8]:
plot_all_clusters_profile_plotly(vars, cluster_avg, database_avg)

## Association Rules

In [276]:
df_items2 = transform_dataset(customer_basket, hierarchical8_notscaled,2)

In [277]:
df_items2

,airpods,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,beer,black beer,...,vacuum cleaner,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17037,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17038,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,True,True,False,False
17039,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17040,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17041,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [278]:
frequent_itemsets, rules = apriori_algorithm(df_items2, min_support=0.2, metric='confidence', confidence_threshold = 0.5)

In [279]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(cake),(cooking oil),0.407288,0.535324,0.233071,0.572252,1.068981,1.0,0.015040,1.086330,0.108872,0.328482,0.079469,0.503817
1,(cake),(oil),0.407288,0.762587,0.329480,0.808961,1.060812,1.0,0.018888,1.242750,0.096718,0.392054,0.195333,0.620509
2,(cake),(tea),0.407288,0.530748,0.233717,0.573837,1.081186,1.0,0.017550,1.101109,0.126688,0.331834,0.091825,0.507095
3,(candy bars),(oil),0.324023,0.762587,0.261237,0.806230,1.057230,1.0,0.014141,1.225231,0.080080,0.316508,0.183827,0.574398
4,(oil),(cooking oil),0.762587,0.535324,0.428647,0.562096,1.050010,1.0,0.020416,1.061136,0.200612,0.493115,0.057613,0.681410
5,(cooking oil),(oil),0.535324,0.762587,0.428647,0.800723,1.050010,1.0,0.020416,1.191377,0.102497,0.493115,0.160635,0.681410
6,(cooking oil),(tea),0.535324,0.530748,0.304542,0.568892,1.071869,1.0,0.020420,1.088480,0.144294,0.399908,0.081287,0.571345
7,(tea),(cooking oil),0.530748,0.535324,0.304542,0.573798,1.071869,1.0,0.020420,1.090270,0.142887,0.399908,0.082796,0.571345
8,(gums),(oil),0.278547,0.762587,0.225091,0.808089,1.059669,1.0,0.012675,1.237104,0.078050,0.275832,0.191660,0.551629
9,(oil),(tea),0.762587,0.530748,0.426828,0.559711,1.054570,1.0,0.022087,1.065782,0.217960,0.492585,0.061722,0.681956
10,(tea),(oil),0.530748,0.762587,0.426828,0.804201,1.054570,1.0,0.022087,1.212538,0.110275,0.492585,0.175284,0.681956
11,"(oil, cooking oil)",(tea),0.428647,0.530748,0.253081,0.590418,1.112426,1.0,0.025577,1.145685,0.176885,0.358312,0.127160,0.533628
12,"(oil, tea)",(cooking oil),0.426828,0.535324,0.253081,0.592934,1.107616,1.0,0.024589,1.141523,0.169512,0.356918,0.123977,0.532847
13,"(tea, cooking oil)",(oil),0.304542,0.762587,0.253081,0.831021,1.089740,1.0,0.020841,1.404990,0.118411,0.310892,0.288251,0.581446