# **CLUSTERING NOTEBOOK**

## Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from umap.umap_ import UMAP
from sklearn.metrics import silhouette_samples, silhouette_score
import matplotlib.cm as cm
from sklearn.decomposition import PCA
import plotly.express as px
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os

# Get the absolute path of the source_code folder
source_code_path = os.path.abspath('../source_code')

# Add the source_code folder to sys.path
if source_code_path not in sys.path:
    sys.path.append(source_code_path)

from utils import *
from preprocessing import *
from clustering import *
from analysis import *

# Get the absolute path of the source_code folder
clustering_outputs_path = os.path.abspath('../clustering_outputs')

# Add the source_code folder to sys.path
if clustering_outputs_path not in sys.path:
    sys.path.append(clustering_outputs_path)

## Load Data

In [3]:
customer_info = load_dataset('../customer_info.csv')

In [4]:
#customer_info.columns

In [5]:
# Calling the clusters
final_clustering_notcaled=load_dataset('../clustering_outputs/final_clustering_notscaled.csv')
final_clustering = load_dataset('../clustering_outputs/final_clustering.csv')

In [6]:
final_clustering.cluster.unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 9, 8], dtype=int64)

In [128]:
customer_basket = load_dataset('../customer_basket.csv')

## Analysis

In [7]:
vars, cluster_avg, database_avg=compute_average_multi(hierarchical8_scaled, 'cluster')

In [8]:
plot_all_clusters_profile_plotly(vars, cluster_avg, database_avg)

## Association Rules

In [129]:
df_items, items_list = transform_dataset(customer_basket, final_clustering,8)

In [130]:
df_items, items_list

(       airpods  almonds  antioxydant juice  asparagus  avocado  babies food  \
 0        False    False              False      False    False        False
 1        False    False              False      False    False        False
 2        False    False              False       True     True        False
 3        False    False              False      False     True        False
 4        False    False              False      False    False        False
 ...        ...      ...                ...        ...      ...          ...
 13435    False    False              False      False    False        False
 13436     True    False              False      False     True        False
 13437    False    False              False      False    False        False
 13438    False    False              False      False    False        False
 13439    False    False              False      False    False        False

        bacon  barbecue sauce   beer  black beer  ...  vacuum cleaner  \
 0      False           False  False       False  ...           False
 1      False           False  False       False  ...            True
 2      False           False  False       False  ...           False
 3      False           False  False       False  ...           False
 4      False           False  False       False  ...           False
 ...      ...             ...    ...         ...  ...             ...
 13435  False           False  False       False  ...           False
 13436  False            True  False       False  ...           False
 13437  False           False  False       False  ...           False
 13438  False           False  False       False  ...           False
 13439  False           False  False       False  ...           False

        vegetables mix  water spray  white wine  whole weat flour  \
 0               False        False       False             False
 1               False        False       False             False
 2               False        False       False             False
 3               False        False       False             False
 4               False        False       False             False
 ...               ...          ...         ...               ...
 13435           False        False       False             False
 13436           False        False       False             False
 13437           False        False       False             False
 13438           False        False       False             False
 13439           False        False       False             False

        whole wheat pasta  whole wheat rice   yams  yogurt cake  zucchini
 0                  False             False  False        False     False
 1                  False             False  False        False     False
 2                  False             False  False        False     False
 3                  False             False  False        False     False
 4                  False             False  False        False     False
 ...                  ...               ...    ...          ...       ...
 13435              False             False  False        False     False
 13436              False             False  False        False     False
 13437              False             False  False        False     False
 13438              False             False  False        False     False
 13439              False             False  False        False     False

 [13440 rows x 164 columns],
 [['chocolate',
   'laptop',
   'frozen smoothie',
   'turkey',
   'gluten free bar',
   'sparkling water',
   'champagne',
   'escalope',
   'burgers',
   'tomato juice'],
  ['iphone 10',
   'ketchup',
   'ham',
   'mint green tea',
   'herb & pepper',
   'fresh tuna',
   'vacuum cleaner'],
  ['cottage cheese',
   'grated cheese',
   'frozen smoothie',
   'avocado',
   'asparagus',
   'sparkling water',
   'champagne',
   'parmesan cheese',
   'blueberries'],
  ['cottage cheese',
   'avocado',
   'fresh tuna',
   'dog food',
   'burger sauce',
   'champagne',
   'metroid prime',
   'half-life 2',
   'phone car charger',
   'bluetooth headphones',
   'half-life: alyx'],
  ['iphone 10',
   'cottage cheese',
   'final fantasy XXII',
   'champagne',
   'blueberries',
   'fresh tuna'],
  ['eggplant',
   'spaghetti',
   'cottage cheese',
   'avocado',
   'bluetooth headphones'],
  ['iphone 10',
   'final fantasy XIX',
   'shallot',
   'spaghetti',
   'fromage blanc',
   'sparkling water',
   'champagne',
   'milk',
   'ham',
   'eggs',
   'green beans',
   'iMac',
   'bluetooth headphones',
   'fresh tuna'],
  ['cotton buds',
   'cat food',
   'avocado',
   'mineral water',
   'catfish',
   'bluetooth headphones',
   'champagne',
   'escalope',
   'minecraft',
   'ham',
   'herb & pepper',
   'fresh tuna'],
  ['final fantasy XIX',
   'spaghetti',
   'rice',
   'french fries',
   'frozen smoothie',
   'avocado',
   'french wine',
   'champagne',
   'almonds',
   'escalope',
   'fresh tuna'],
  ['iphone 10',
   'spaghetti',
   'frozen smoothie',
   'mineral water',
   'chili',
   'fresh tuna'],
  ['ring light',
   'frozen smoothie',
   'french wine',
   'champagne',
   'herb & pepper',
   'blueberries',
   'corn',
   'bluetooth headphones',
   'fresh tuna'],
  ['salad', 'tomato juice', 'french wine', 'salmon'],
  ['hot dogs',
   'cottage cheese',
   'turkey',
   'frozen smoothie',
   'french wine',
   'low fat yogurt',
   'champagne',
   'megaman zero 2',
   'fresh tuna'],
  ['champagne', 'shrimp', 'salmon'],
  ['meatballs',
   'cottage cheese',
   'mint green tea',
   'avocado',
   'champagne',
   'pancakes',
   'iMac',
   'fresh tuna'],
  ['black beer',
   'iphone 10',
   'rice',
   'french wine',
   'vegetables mix',
   'champagne',
   'hand protein bar',
   'almonds',
   'half-life 2',
   'salmon',
   'eggs',
   'bluetooth headphones',
   'fresh tuna'],
  ['iphone 10',
   'whole wheat rice',
   'cottage cheese',
   'laptop',
   'pancakes',
   'salmon',
   'final fantasy XX',
   'bluetooth headphones',
   'fresh tuna'],
  ['frozen smoothie', 'sparkling water', 'almonds', 'iMac', 'fresh tuna'],
  ['pickles',
   'chutney',
   'spaghetti',
   'beer',
   'avocado',
   'black tea',
   'ratchet & clank',
   'champagne',
   'nonfat milk',
   'shrimp',
   'blueberries',
   'salad',
   'red wine',
   'bluetooth headphones'],
  ['frozen smoothie', 'champagne', 'brownies', 'fresh tuna', 'tea'],
  ['spaghetti',
   'cottage cheese',
   'phone charger',
   'frozen smoothie',
   'mineral water',
   'fromage blanc',
   'champagne',
   'nonfat milk',
   'almonds',
   'milk',
   'phone car charger',
   'body spray',
   'fresh tuna',
   'protein bar'],
  ['spaghetti',
   'cottage cheese',
   'frozen smoothie',
   'champagne',
   'melons',
   'escalope',
   'salmon',
   'chicken',
   'herb & pepper',
   'fresh tuna'],
  ['spaghetti',
   'cottage cheese',
   'strong cheese',
   'frozen smoothie',
   'fromage blanc',
   'sparkling water',
   'fresh bread',
   'champagne',
   'melons',
   'burgers',
   'bluetooth headphones',
   'fresh tuna'],
  ['cottage cheese',
   'ring light',
   'frozen smoothie',
   'laptop',
   'fromage blanc',
   'airpods',
   'champagne',
   'half-life 2',
   'green beans',
   'water spray',
   'bluetooth headphones',
   'fresh tuna'],
  ['soda',
   'laptop',
   'seabass',
   'avocado',
   'gluten free bar',
   'champagne',
   'shrimp',
   'parmesan cheese',
   'yogurt cake',
   'herb & pepper',
   'sandwich',
   'phone car charger',
   'bluetooth headphones',
   'fresh tuna'],
  ['avocado', 'champagne', 'nonfat milk', 'ground beef', 'metroid fusion'],
  ['yams',
   'soup',
   'phone charger',
   'grated cheese',
   'frozen smoothie',
   'avocado',
   'deodorant',
   'almonds',
   'herb & pepper',
   'blueberries',
   'portal 2',
   'phone car charger',
   'bluetooth headphones',
   'fresh tuna'],
  ['meatballs',
   'spaghetti',
   'whole wheat rice',
   'avocado',
   'gluten free bar',
   'champagne',
   'salmon',
   'bluetooth headphones'],
  ['black beer',
   'meatballs',
   'cottage cheese',
   'frozen smoothie',
   'avocado',
   'bacon',
   'champagne',
   'almonds',
   'chicken',
   'fresh tuna'],
  ['strong cheese',
   'sparkling water',
   'champagne',
   'shrimp',
   'nonfat milk',
   'toothpaste',
   'pepper',
   'eggs',
   'burgers',
   'iMac',
   'bluetooth headphones',
   'fresh tuna'],
  ['rice', 'asparagus', 'champagne', 'melons', 'ratchet & clank 2'],
  ['cake',
   'light cream',
   'grated cheese',
   'strong cheese',
   'samsung galaxy 10',
   'avocado',
   'champagne',
   'brownies',
   'melons',
   'salmon',
   'bluetooth headphones',
   'fresh tuna'],
  ['champagne', 'avocado', 'cat food', 'chicken'],
  ['spaghetti',
   'frozen smoothie',
   'avocado',
   'ketchup',
   'asparagus',
   'champagne',
   'portal 2',
   'salmon',
   'bluetooth headphones'],
  ['phone charger',
   'french fries',
   'oil',
   'airpods',
   'deodorant',
   'final fantasy XX',
   'megaman zero',
   'pasta',
   'spinach',
   'mint green tea',
   'barbecue sauce'],
  ['antioxydant juice',
   'cottage cheese',
   'spaghetti',
   'oil',
   'fresh tuna',
   'deodorant',
   'ratchet & clank',
   'shrimp',
   'toothpaste',
   'yogurt cake',
   'light mayo',
   'barbecue sauce',
   'cooking oil'],
  ['chocolate',
   'antioxydant juice',
   'mint green tea',
   'oil',
   'avocado',
   'deodorant',
   'airpods',
   'whole weat flour',
   'brownies',
   'salmon',
   'spinach',
   'chicken',
   'tomato juice',
   'barbecue sauce'],
  ['pickles',
   'cake',
   'napkins',
   'pokemon violet',
   'frozen vegetables',
   'flax seed',
   'nonfat milk'],
  ['soup',
   'oil',
   'flax seed',
   'deodorant',
   'ham',
   'ground beef',
   'cologne',
   'body spray',
   'barbecue sauce'],
  ['chocolate',
   'napkins',
   'samsung galaxy 10',
   'bacon',
   'oil',
   'fresh tuna',
   'sparkling water',
   'ham',
   'cologne',
   'barbecue sauce',
   'cooking oil'],
  ['oil',
   'pokemon scarlet',
   'ratchet & clank',
   'brownies',
   'melons',
   'green beans',
   'fresh tuna'],
  ['napkins',
   'antioxydant juice',
   'oatmeal',
   'turkey',
   'seabass',
   'fromage blanc',
   'pokemon sword',
   'ratchet & clank',
   'milk',
   'fresh bread',
   'muffins',
   'final fantasy XX',
   'chicken'],
  ['final fantasy XIX',
   'napkins',
   'eggplant',
   'cologne',
   'oil',
   'ratchet & clank',
   'milk',
   'pasta',
   'babies food',
   'melons',
   'muffins',
   'extra dark chocolate',
   'burgers',
   'ratchet & clank 2'],
  ['grated cheese',
   'olive oil',
   'strawberries',
   'dog food',
   'megaman zero 2',
   'pokemon sword',
   'shower gel',
   'toothpaste',
   'whole weat flour',
   'minecraft',
   'babies food',
   'toilet paper',
   'ratchet & clank 2'],
  ['iPad',
   'phone charger',
   'dog food',
   'catfish',
   'ratchet & clank',
   'babies food',
   'minecraft',
   'pet food',
   'ground beef',
   'burgers',
   'body spray',
   'cooking oil'],
  ['soup',
   'samsung galaxy 10',
   'french fries',
   'cereals',
   'strawberries',
   'vegetables mix',
   'milk',
   'ratchet & clank 2',
   'butter',
   'barbecue sauce',
   'zucchini'],
  ['ketchup',
   'flax seed',
   'ratchet & clank',
   'minecraft',
   'babies food',
   'ratchet & clank 3'],
  ['tooth brush',
   'shallot',
   'zucchini',
   'soda',
   'rice',
   'cereals',
   'ratchet & clank',
   'nonfat milk',
   'babies food',
   'minecraft',
   'pet food',
   'half-life 2',
   'ratchet & clank 2'],
  ['frozen smoothie', 'tomatoes', 'fresh tuna'],
  ['black beer',
   'french fries',
   'avocado',
   'airpods',
   'champagne',
   'almonds',
   'melons',
   'muffins',
   'half-life: alyx'],
  ['metroid prime', 'champagne', 'fresh tuna'],
  ['spaghetti',
   'cottage cheese',
   'grated cheese',
   'laptop',
   'frozen smoothie',
   'strong cheese',
   'sparkling water',
   'low fat yogurt',
   'champagne',
   'parmesan cheese',
   'salmon',
   'light mayo',
   'half-life: alyx'],
  ['soup',
   'cottage cheese',
   'frozen smoothie',
   'avocado',
   'champagne',
   'shrimp',
   'almonds',
   'ham',
   'red wine',
   'tomato sauce',
   'fresh tuna'],
  ['shallot',
   'cottage cheese',
   'beer',
   'grated cheese',
   'mint green tea',
   'frozen smoothie',
   'avocado',
   'champagne',
   'nonfat milk',
   'corn',
   'blueberries',
   'phone car charger',
   'iMac',
   'fresh tuna'],
  ['iphone 10',
   'spaghetti',
   'cottage cheese',
   'french wine',
   'honey',
   'shower gel',
   'spinach',
   'fresh tuna'],
  ['iphone 10',
   'candy bars',
   'meatballs',
   'turkey',
   'strawberries',
   'shower gel',
   'shrimp',
   'champagne',
   'vacuum cleaner',
   'bluetooth headphones',
   'fresh tuna'],
  ['iphone 10',
   'yams',
   'grated cheese',
   'frozen vegetables',
   'final fantasy XXII',
   'champagne',
   'brownies',
   'escalope',
   'bluetooth headphones'],
  ['tooth brush',
   'iPad',
   'gluten free bar',
   'shower gel',
   'champagne',
   'salmon'],
  ['frozen smoothie',
   'shower gel',
   'champagne',
   'brownies',
   'tomatoes',
   'half-life: alyx',
   'phone car charger',
   'bluetooth headphones',
   'fresh tuna'],
  ['whole wheat pasta',
   'cooking oil',
   'grated cheese',
   'frozen smoothie',
   'fromage blanc',
   'shower gel',
   'champagne',
   'pancakes',
   'bluetooth headphones',
   'fresh tuna'],
  ['candy bars',
   'dessert wine',
   'tooth brush',
   'cottage cheese',
   'frozen smoothie',
   'asparagus',
   'champagne',
   'whole weat flour',
   'blueberries',
   'salmon',
   'green beans',
   'bluetooth headphones',
   'fresh tuna'],
  ['dessert wine',
   'spaghetti',
   'cottage cheese',
   'oil',
   'sparkling water',
   'pet food',
   'iMac',
   'burgers',
   'megaman zero 4'],
  ['chutney',
   'frozen smoothie',
   'champagne',
   'toothpaste',
   'blueberries',
   'sandwich',
   'metroid prime',
   'water spray',
   'herb & pepper',
   'fresh tuna'],
  ['spaghetti',
   'phone charger',
   'grated cheese',
   'champagne',
   'portal 2',
   'fresh tuna'],
  ['spaghetti',
   'cottage cheese',
   'avocado',
   'dog food',
   'champagne',
   'blueberries',
   'ground beef',
   'fresh tuna'],
  ['spaghetti',
   'samsung galaxy 10',
   'frozen smoothie',
   'final fantasy XXII',
   'champagne',
   'blueberries',
   'salmon',
   'fresh tuna'],
  ['yams',
   'mashed potato',
   'laptop',
   'frozen smoothie',
   'strong cheese',
   'fromage blanc',
   'dog food',
   'champagne',
   'brownies',
   'almonds',
   'bluetooth headphones',
   'fresh tuna'],
  ['spaghetti',
   'frozen smoothie',
   'avocado',
   'final fantasy XX',
   'gluten free bar',
   'strawberries',
   'sparkling water',
   'champagne',
   'escalope',
   'blueberries',
   'salmon',
   'yogurt cake',
   'vacuum cleaner',
   'bluetooth headphones',
   'fresh tuna'],
  ['soda',
   'cake',
   'oatmeal',
   'phone charger',
   'samsung galaxy 10',
   'mineral water',
   'avocado',
   'champagne',
   'escalope',
   'ham',
   'vacuum cleaner',
   'fresh tuna'],
  ['whole wheat rice',
   'phone charger',
   'champagne',
   'blueberries',
   'fresh tuna'],
  ['turkey',
   'laptop',
   'portal',
   'gluten free bar',
   'champagne',
   'brownies',
   'gums',
   'ground beef',
   'phone car charger',
   'green beans'],
  ['spaghetti',
   'cottage cheese',
   'ring light',
   'fresh bread',
   'champagne',
   'nonfat milk',
   'half-life: alyx',
   'phone car charger',
   'bluetooth headphones',
   'fresh tuna'],
  ['pancakes', 'champagne', 'tomato sauce'],
  ['eggplant',
   'mashed potato',
   'champagne',
   'brownies',
   'spinach',
   'iMac',
   'protein bar'],
  ['cottage cheese',
   'beer',
   'grated cheese',
   'turkey',
   'frozen smoothie',
   'champagne',
   'tomatoes',
   'ham',
   'megaman zero 4',
   'bluetooth headphones',
   'fresh tuna'],
  ['strong cheese', 'mayonnaise', 'ratchet & clank', 'fresh tuna'],
  ['iphone 10',
   'megaman zero 3',
   'spaghetti',
   'cottage cheese',
   'phone charger',
   'gluten free bar',
   'burger sauce',
   'champagne',
   'brownies',
   'minecraft',
   'yogurt cake',
   'salmon',
   'eggs',
   'ground beef',
   'bluetooth headphones',
   'fresh tuna'],
  ['soda',
   'hot dogs',
   'oatmeal',
   'avocado',
   'black tea',
   'asparagus',
   'toothpaste',
   'muffins',
   'salmon',
   'phone car charger'],
  ['asparagus', 'vegetables mix'],
  ['chutney',
   'spaghetti',
   'cottage cheese',
   'frozen smoothie',
   'asparagus',
   'burger sauce',
   'champagne',
   'nonfat milk',
   'ham',
   'ground beef',
   'half-life 2',
   'blueberries',
   'butter',
   'bluetooth headphones'],
  ['mashed potato',
   'frozen smoothie',
   'gadget for tiktok streaming',
   'avocado',
   'fromage blanc',
   'shower gel',
   'champagne',
   'nonfat milk',
   'parmesan cheese',
   'shrimp',
   'ham',
   'salmon',
   'fresh tuna'],
  ['pokemon sword', 'champagne', 'shrimp', 'ham', 'chutney', 'fresh tuna'],
  ['cottage cheese',
   'champagne',
   'energy drink',
   'final fantasy XX',
   'fresh tuna'],
  ['spaghetti',
   'cottage cheese',
   'laptop',
   'frozen smoothie',
   'avocado',
   'sparkling water',
   'champagne',
   'hand protein bar',
   'olive oil',
   'ratchet & clank 2',
   'tea'],
  ['final fantasy XIX',
   'shallot',
   'spaghetti',
   'cooking oil',
   'grated cheese',
   'laptop',
   'ring light',
   'oil',
   'shower gel',
   'champagne',
   'corn',
   'cat food',
   'fresh tuna'],
  ['iPad',
   'avocado',
   'fromage blanc',
   'catfish',
   'iMac',
   'tomato juice',
   'green grapes'],
  ['razor',
   'avocado',
   'champagne',
   'ham',
   'half-life: alyx',
   'ratchet & clank 3',
   'iMac',
   'toilet paper',
   'fresh tuna'],
  ['spaghetti',
   'frozen smoothie',
   'asparagus',
   'champagne',
   'parmesan cheese',
   'final fantasy XX',
   'fresh tuna'],
  ['protein bar',
   'shallot',
   'spaghetti',
   'turkey',
   'strong cheese',
   'fromage blanc',
   'dog food',
   'shower gel',
   'champagne',
   'ham',
   'vacuum cleaner',
   'bluetooth headphones',
   'fresh tuna'],
  ['champagne', 'frozen smoothie', 'blueberries'],
  ['champagne', 'bluetooth headphones', 'fresh tuna'],
  ['black tea', 'champagne', 'half-life: alyx', 'tomato juice', 'fresh tuna'],
  ['iphone 10',
   'frozen smoothie',
   'avocado',
   'champagne',
   'iMac',
   'bluetooth headphones',
   'fresh tuna'],
  ['champagne', 'frozen smoothie', 'black tea'],
  ['iphone 10',
   'hot dogs',
   'phone charger',
   'laptop',
   'frozen smoothie',
   'avocado',
   'fromage blanc',
   'toilet paper',
   'champagne',
   'half-life: alyx',
   'salmon',
   'iMac',
   'fresh tuna',
   'cooking oil'],
  ['megaman zero 3',
   'spaghetti',
   'cottage cheese',
   'green grapes',
   'avocado',
   'fromage blanc',
   'gluten free bar',
   'final fantasy XXII',
   'champagne',
   'megaman zero 2',
   'bluetooth headphones',
   'fresh tuna',
   'metroid fusion'],
  ['meatballs',
   'cottage cheese',
   'cat food',
   'champagne',
   'megaman zero 4',
   'herb & pepper'],
  ['iphone 10',
   'candy bars',
   'parmesan cheese',
   'carrots',
   'escalope',
   'bluetooth headphones',
   'fresh tuna'],
  ['champagne', 'cottage cheese'],
  ['spaghetti',
   'strong cheese',
   'laptop',
   'champagne',
   'salmon',
   'phone car charger',
   'fresh tuna',
   'chocolate bread'],
  ['grated cheese',
   'gadget for tiktok streaming',
   'champagne',
   'herb & pepper',
   'tea'],
  ['cottage cheese',
   'grated cheese',
   'turkey',
   'frozen smoothie',
   'gluten free bar',
   'pokemon scarlet',
   'champagne'],
  ['meatballs',
   'spaghetti',
   'phone charger',
   'avocado',
   'burger sauce',
   'shower gel',
   'champagne',
   'almonds',
   'herb & pepper',
   'fresh tuna',
   'chocolate bread'],
  ['iPad',
   'frozen smoothie',
   'fromage blanc',
   'shrimp',
   'gums',
   'muffins',
   'melons',
   'salmon',
   'butter',
   'fresh tuna'],
  ['napkins',
   'cotton buds',
   'cottage cheese',
   'laptop',
   'avocado',
   'almonds',
   'burgers',

In [131]:
frequent_itemsets, rules = apriori_algorithm(df_items, min_support=0.15, metric='confidence', confidence_threshold = 0.5)

In [132]:
rules = rules.sort_values('lift', ascending=False)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
21,(spaghetti),"(fresh tuna, champagne)",0.335789,0.448065,0.180134,0.536450,1.197259,1.0,0.029679,1.190669,0.248051,0.298373,0.160136,0.469238
18,(frozen smoothie),"(fresh tuna, champagne)",0.285193,0.448065,0.152158,0.533525,1.190729,1.0,0.024372,1.183202,0.224087,0.261844,0.154836,0.436556
20,"(spaghetti, champagne)",(fresh tuna),0.281250,0.542188,0.180134,0.640476,1.181282,1.0,0.027644,1.273386,0.213512,0.280014,0.214692,0.486356
12,"(fresh tuna, champagne)",(bluetooth headphones),0.448065,0.427381,0.225893,0.504151,1.179630,1.0,0.034398,1.154826,0.275896,0.347766,0.134069,0.516351
15,(bluetooth headphones),"(fresh tuna, champagne)",0.427381,0.448065,0.225893,0.528552,1.179630,1.0,0.034398,1.170721,0.265930,0.347766,0.145825,0.516351
17,"(champagne, frozen smoothie)",(fresh tuna),0.239137,0.542188,0.152158,0.636279,1.173540,1.0,0.022501,1.258691,0.194355,0.241840,0.205524,0.458458
14,"(bluetooth headphones, champagne)",(fresh tuna),0.355655,0.542188,0.225893,0.635146,1.171452,1.0,0.033061,1.254784,0.227143,0.336175,0.203050,0.525889
11,(spaghetti),(fresh tuna),0.335789,0.542188,0.208631,0.621316,1.145943,1.0,0.026571,1.208957,0.191741,0.311694,0.172841,0.503056
19,"(fresh tuna, spaghetti)",(champagne),0.208631,0.753497,0.180134,0.863409,1.145870,1.0,0.022931,1.804685,0.160861,0.230352,0.445887,0.551237
10,(frozen smoothie),(fresh tuna),0.285193,0.542188,0.176860,0.620141,1.143776,1.0,0.022232,1.205217,0.175856,0.271875,0.170274,0.473169
13,"(fresh tuna, bluetooth headphones)",(champagne),0.262277,0.753497,0.225893,0.861277,1.143039,1.0,0.028268,1.776939,0.169629,0.285983,0.437234,0.580535
16,"(fresh tuna, frozen smoothie)",(champagne),0.176860,0.753497,0.152158,0.860328,1.141780,1.0,0.018894,1.764872,0.150855,0.195525,0.433387,0.531132
3,(bluetooth headphones),(fresh tuna),0.427381,0.542188,0.262277,0.613684,1.131866,1.0,0.030556,1.185072,0.203457,0.370818,0.156169,0.548711
1,(avocado),(fresh tuna),0.247619,0.542188,0.151414,0.611478,1.127799,1.0,0.017158,1.178345,0.150611,0.237179,0.151352,0.445371
7,(frozen smoothie),(champagne),0.285193,0.753497,0.239137,0.838508,1.112822,1.0,0.024244,1.526407,0.141833,0.299088,0.344867,0.577939
4,(cottage cheese),(champagne),0.219643,0.753497,0.184003,0.837737,1.111799,1.0,0.018503,1.519158,0.128860,0.233170,0.341741,0.540968
9,(spaghetti),(champagne),0.335789,0.753497,0.281250,0.837580,1.111591,1.0,0.028234,1.517692,0.151139,0.348066,0.341105,0.605420
0,(avocado),(champagne),0.247619,0.753497,0.206548,0.834135,1.107018,1.0,0.019967,1.486163,0.128488,0.259949,0.327126,0.554127
2,(bluetooth headphones),(champagne),0.427381,0.753497,0.355655,0.832173,1.104414,1.0,0.033624,1.468790,0.165105,0.430980,0.319167,0.652089
6,(champagne),(fresh tuna),0.753497,0.542188,0.448065,0.594648,1.096757,1.0,0.039529,1.129420,0.357890,0.528617,0.114589,0.710526
5,(fresh tuna),(champagne),0.542188,0.753497,0.448065,0.826403,1.096757,1.0,0.039529,1.419974,0.192701,0.528617,0.295762,0.710526
8,(laptop),(champagne),0.196503,0.753497,0.161905,0.823930,1.093475,1.0,0.013840,1.400031,0.106391,0.205438,0.285730,0.519401

In [127]:
rules = rules[(rules['support'] > 0.1) & (rules['confidence'] > 0.5) & (rules['lift'] >= 1.2)]
rules.sort_values(by = 'confidence', ascending=False)

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, representativity, leverage, conviction, zhangs_metric, jaccard, certainty, kulczynski]
Index: []

Assosiation Rules

Cluster 0:
(pasta, meatballs) (oil)

- Confidence: 88.9% of those who bought pasta and meatballs also bought oil
- Support: This rule appears in 15% of all transactions in the cluster 
- Lift:The likelihood of buying oil increases by 1.2 if pasta and meatballs are bought.

Cluster 1:
(cauliflower, carrots)	(tomatoes, asparagus)

- Confidence: 79.2% of those who bought cauliflower and carrots also bought tomatoes and asparagus.
- Support: This rule appears in 8% of all transactions in the cluster 
- Lift:The likelihood of buying tomatoes and asparagus increases by 1.26 if cauliflower and carrots are bought.

Cluster 2:
(minecraft, cooking oil)	(babies food, ratchet & clank)

- Confidence: 55.8% of those who bought minecraft and cooking oil also bought babies food, ratchet and clank
- Support: This rule appears in 9.2% of all transactions in the cluster 
- Lift:The likelihood of buying babies food, ratchet and clank increases by 1.2 if minecraft and cooking oil are bought.

CLuster 3:
(pancakes)	(energy drink)

- Confidence: 79.7% of those who bought pancakes also bought energy drink
- Support: This rule appears in 28.6% of all transactions in the cluster 
- Lift:The likelihood of buying energy drink increases by 1.62 if pancakes are bought.

CLuster 4:
(cake, cooking oil)	(oil, tea)	

- Confidence: 51.6% of those who bought cake and cooking oil also bought oil and tea.
- Support: This rule appears in 12% of all transactions in the cluster 
- Lift:The likelihood of buying oil and tea increases by 1.22 if cake and cooking oil are bought.

CLuster 5:
(salt)	(beer)	0.341256	0.655605	0.280717	0.822602	1.254721
(white wine)	(beer)	0.534081	0.655605	0.395067	0.739715	1.128292

- Confidence: 88.9% of those who bought pasta and meatballs also bought oil
- Support: This rule appears in 15% of all transactions in the cluster 
- Lift:The likelihood of buying oil increases by 1.2 if pasta and meatballs are bought.

Cluster 6:
(gums)	(oil)	0.268779	0.723556	0.223812	0.832700	1.150843
(candy bars, cooking oil)	(oil)	0.175779	0.723556	0.153807	0.875000	1.209304

- Confidence: 88.9% of those who bought pasta and meatballs also bought oil
- Support: This rule appears in 15% of all transactions in the cluster 
- Lift:The likelihood of buying oil increases by 1.2 if pasta and meatballs are bought.

Cluster 7:
(cake, cooking oil)	(oil)	0.258852	0.770106	0.222559	0.859795	1.116463

- Confidence: 88.9% of those who bought pasta and meatballs also bought oil
- Support: This rule appears in 15% of all transactions in the cluster 
- Lift:The likelihood of buying oil increases by 1.2 if pasta and meatballs are bought.

Cluster 8:
(spaghetti)	(fresh tuna, champagne)	0.335789	0.448065	0.180134	0.536450	1.19725

- Confidence: 88.9% of those who bought pasta and meatballs also bought oil
- Support: This rule appears in 15% of all transactions in the cluster 
- Lift:The likelihood of buying oil increases by 1.2 if pasta and meatballs are bought.

## Eclat Algorithm

In [39]:
items_list2

[['soup',
  'shallot',
  'cake',
  'fresh bread',
  'cream',
  'carrots',
  'babies food',
  'ham',
  'cookies',
  'salad',
  'tomato sauce',
  'cooking oil',
  'tea'],
 ['candy bars', 'soup', 'napkins', 'rice', 'oil', 'tea'],
 ['zucchini',
  'grated cheese',
  'ketchup',
  'oil',
  'pokemon scarlet',
  'milk',
  'water spray',
  'chicken',
  'cooking oil',
  'tea'],
 ['candy bars',
  'napkins',
  'frozen smoothie',
  'oil',
  'ham',
  'phone car charger',
  'cologne',
  'iMac',
  'tea'],
 ['cake', 'cream', 'corn', 'blueberries', 'burgers'],
 ['oil', 'babies food', 'cooking oil'],
 ['soup', 'protein bar', 'oil', 'toothpaste', 'ham', 'cooking oil', 'tea'],
 ['candy bars',
  'cake',
  'whole wheat rice',
  'oil',
  'portal',
  'black tea',
  'fresh bread',
  'ham',
  'green beans',
  'cooking oil'],
 ['meatballs',
  'cottage cheese',
  'french fries',
  'turkey',
  'oil',
  'chocolate bread',
  'tomatoes',
  'cologne',
  'cooking oil',
  'tea'],
 ['soup',
  'cooking oil',
  'cereals',
  'oil',
  'dog food',
  'deodorant',
  'tomatoes',
  'yogurt cake',
  'pet food',
  'salmon',
  'olive oil',
  'fresh tuna',
  'tea'],
 ['oil', 'pasta', 'blueberries', 'olive oil', 'mint', 'tomato juice', 'tea'],
 ['whole wheat rice',
  'meatballs',
  'frozen smoothie',
  'oil',
  'ketchup',
  'gums',
  'toothpaste',
  'cooking oil',
  'green grapes',
  'tea'],
 ['cake',
  'napkins',
  'phone charger',
  'french fries',
  'oil',
  'ketchup',
  'shower gel',
  'gums',
  'whole weat flour',
  'muffins',
  'pepper',
  'burgers',
  'bluetooth headphones',
  'cooking oil'],
 ['soup',
  'napkins',
  'oatmeal',
  'french fries',
  'gadget for tiktok streaming',
  'gums',
  'cooking oil',
  'mushroom cream sauce',
  'tea'],
 ['soup',
  'megaman zero 3',
  'french fries',
  'turkey',
  'oil',
  'ketchup',
  'gums',
  'milk',
  'babies food',
  'toilet paper',
  'salt',
  'tea'],
 ['cream', 'cereals', 'rice', 'napkins'],
 ['soup', 'oatmeal', 'oil', 'green beans', 'metroid fusion', 'tea'],
 ['candy bars',
  'cake',
  'strong cheese',
  'cereals',
  'oil',
  'final fantasy XXII',
  'fresh bread',
  'cooking oil',
  'tea'],
 ['candy bars',
  'megaman zero 3',
  'grated cheese',
  'oil',
  'fresh bread',
  'pokemon scarlet',
  'babies food',
  'salmon',
  'toilet paper',
  'cooking oil'],
 ['ketchup', 'yogurt cake', 'cooking oil', 'oil'],
 ['shampoo',
  'soup',
  'shallot',
  'napkins',
  'oil',
  'gadget for tiktok streaming',
  'toothpaste',
  'half-life 2',
  'cooking oil'],
 ['oatmeal', 'frozen vegetables', 'oil', 'sandwich', 'cooking oil'],
 ['candy bars',
  'napkins',
  'rice',
  'pokemon shield',
  'oil',
  'ketchup',
  'asparagus',
  'shower gel',
  'milk',
  'parmesan cheese',
  'escalope',
  'cooking oil',
  'tea'],
 ['burgers',
  'napkins',
  'turkey',
  'pokemon shield',
  'oil',
  'dog food',
  'shower gel',
  'muffins',
  'corn',
  'ground beef',
  'cologne',
  'cooking oil',
  'tea'],
 ['candy bars',
  'napkins',
  'spaghetti',
  'mashed potato',
  'strong cheese',
  'frozen vegetables',
  'oil',
  'avocado',
  'gums',
  'babies food',
  'tomato sauce'],
 ['candy bars',
  'pickles',
  'final fantasy XIX',
  'chocolate',
  'soda',
  'cottage cheese',
  'cereals',
  'oil',
  'honey',
  'gums',
  'cream',
  'cookies',
  'olive oil',
  'cooking oil',
  'tea'],
 ['whole wheat pasta',
  'napkins',
  'oil',
  'megaman zero 2',
  'minecraft',
  'toilet paper',
  'cooking oil',
  'tea'],
 ['protein bar',
  'whole wheat rice',
  'oatmeal',
  'hot dogs',
  'oil',
  'shower gel',
  'milk',
  'burgers',
  'tomato sauce',
  'cooking oil',
  'green grapes'],
 ['soup',
  'cake',
  'oatmeal',
  'grated cheese',
  'oil',
  'cream',
  'muffins',
  'pet food',
  'eggs',
  'tea'],
 ['candy bars',
  'tooth brush',
  'cake',
  'cottage cheese',
  'grated cheese',
  'strong cheese',
  'oil',
  'portal',
  'fresh bread',
  'whole weat flour',
  'parmesan cheese',
  'eggs'],
 ['cereals', 'whole wheat rice', 'iPad', 'tea'],
 ['burgers',
  'candy bars',
  'cake',
  'soup',
  'mashed potato',
  'ring light',
  'olive oil',
  'ketchup',
  'gluten free bar',
  'pet food',
  'babies food',
  'chili',
  'cologne',
  'toilet paper',
  'cooking oil',
  'tea'],
 ['cake',
  'energy bar',
  'flax seed',
  'sparkling water',
  'honey',
  'gums',
  'muffins',
  'babies food',
  'melons',
  'butter',
  'cooking oil',
  'tea'],
 ['candy bars',
  'napkins',
  'cooking oil',
  'oil',
  'fresh bread',
  'gums',
  'pasta',
  'muffins',
  'chicken',
  'body spray'],
 ['tooth brush',
  'cotton buds',
  'turkey',
  'oil',
  'mayonnaise',
  'extra dark chocolate',
  'toilet paper',
  'cooking oil'],
 ['soup',
  'mashed potato',
  'strong cheese',
  'oil',
  'deodorant',
  'half-life 2',
  'olive oil',
  'cooking oil',
  'tea'],
 ['cake',
  'cottage cheese',
  'french fries',
  'ring light',
  'vegetables mix',
  'shrimp',
  'milk',
  'spinach'],
 ['candy bars',
  'napkins',
  'turkey',
  'oil',
  'strawberries',
  'ketchup',
  'burger sauce',
  'final fantasy XXII',
  'fresh bread',
  'pet food',
  'escalope',
  'ratchet & clank 3',
  'tea'],
 ['meatballs', 'beer', 'oil', 'olive oil', 'zucchini'],
 ['soup',
  'tooth brush',
  'napkins',
  'french fries',
  'turkey',
  'oil',
  'pokemon shield',
  'strawberries',
  'asparagus',
  'mayonnaise',
  'gums',
  'pasta',
  'escalope',
  'eggs',
  'burgers',
  'mint',
  'cooking oil',
  'tea'],
 ['candy bars',
  'cake',
  'rice',
  'strong cheese',
  'pokemon violet',
  'oil',
  'milk',
  'escalope',
  'tomato sauce',
  'cooking oil',
  'tea'],
 ['candy bars',
  'soup',
  'whole wheat rice',
  'oil',
  'flax seed',
  'ratchet & clank',
  'milk',
  'cream',
  'gums',
  'pet food',
  'mayonnaise',
  'yogurt cake',
  'tea'],
 ['candy bars', 'cake', 'oatmeal', 'hot dogs', 'french fries', 'butter'],
 ['cake',
  'phone charger',
  'strong cheese',
  'oil',
  'asparagus',
  'gums',
  'muffins',
  'ham',
  'green grapes'],
 ['cake', 'french fries', 'oil', 'muffins', 'sandwich', 'cooking oil', 'tea'],
 ['whole weat flour', 'muffins', 'corn', 'butter'],
 ['tooth brush',
  'shallot',
  'mashed potato',
  'cottage cheese',
  'french fries',
  'strong cheese',
  'oil',
  'gums',
  'yogurt cake',
  'megaman zero'],
 ['cake',
  'cologne',
  'grated cheese',
  'gums',
  'metroid prime',
  'sandwich',
  'light mayo',
  'cooking oil',
  'tea'],
 ['pickles',
  'cottage cheese',
  'french fries',
  'oil',
  'ketchup',
  'gums',
  'sandwich',
  'burgers',
  'tea'],
 ['yams',
  'strong cheese',
  'cereals',
  'oil',
  'tomatoes',
  'cologne',
  'body spray',
  'butter',
  'cooking oil',
  'cauliflower',
  'tea'],
 ['cottage cheese',
  'oil',
  'catfish',
  'megaman zero 4',
  'barbecue sauce',
  'cooking oil',
  'tea'],
 ['cake',
  'oatmeal',
  'megaman zero 3',
  'oil',
  'parmesan cheese',
  'muffins',
  'cookies',
  'cooking oil',
  'tea'],
 ['pickles',
  'soup',
  'cake',
  'french fries',
  'oil',
  'deodorant',
  'shower gel',
  'muffins',
  'sandwich',
  'cat food',
  'cooking oil',
  'cauliflower',
  'tea'],
 ['yams',
  'cake',
  'napkins',
  'rice',
  'french fries',
  'fromage blanc',
  'gums',
  'mayonnaise',
  'pet food',
  'salad',
  'cooking oil'],
 ['cake',
  'spaghetti',
  'rice',
  'muffins',
  'babies food',
  'yogurt cake',
  'body spray',
  'tomato sauce',
  'cooking oil'],
 ['soup',
  'meatballs',
  'spaghetti',
  'rice',
  'oatmeal',
  'oil',
  'toothpaste',
  'milk',
  'muffins',
  'cooking oil',
  'tea'],
 ['candy bars',
  'cake',
  'eggplant',
  'french fries',
  'cereals',
  'oil',
  'frozen smoothie',
  'asparagus',
  'pokemon scarlet',
  'butter',
  'cooking oil',
  'tea'],
 ['cake',
  'whole wheat pasta',
  'oil',
  'fresh bread',
  'whole weat flour',
  'carrots',
  'light mayo',
  'tomato juice',
  'tomato sauce'],
 ['ketchup', 'oil', 'pasta', 'muffins', 'green beans', 'tea'],
 ['napkins',
  'eggplant',
  'oil',
  'fresh bread',
  'parmesan cheese',
  'muffins',
  'salmon',
  'tea'],
 ['cake',
  'french fries',
  'fresh bread',
  'sandwich',
  'toilet paper',
  'butter',
  'tea'],
 ['bramble',
  'soup',
  'cake',
  'napkins',
  'oil',
  'gadget for tiktok streaming',
  'fresh bread',
  'tomatoes',
  'canned_tuna',
  'blueberries',
  'mint',
  'butter',
  'cooking oil',
  'tea'],
 ['cake',
  'spaghetti',
  'french fries',
  'oil',
  'fresh bread',
  'gums',
  'pet food',
  'half-life: alyx',
  'cooking oil',
  'tea'],
 ['candy bars',
  'napkins',
  'meatballs',
  'ring light',
  'oil',
  'pancakes',
  'nonfat milk',
  'chili',
  'cookies',
  'protein bar'],
 ['candy bars', 'napkins', 'sparkling water', 'muffins', 'cooking oil'],
 ['burgers',
  'cake',
  'cereals',
  'oil',
  'cookies',
  'body spray',
  'salad',
  'barbecue sauce',
  'cooking oil'],
 ['candy bars',
  'cake',
  'french fries',
  'mineral water',
  'oil',
  'asparagus',
  'low fat yogurt',
  'fresh bread',
  'shrimp',
  'gums',
  'cream',
  'pet food',
  'portal 2',
  'cooking oil',
  'metroid fusion'],
 ['cake', 'whole wheat rice', 'muffins', 'cooking oil', 'tea'],
 ['soup',
  'cake',
  'oatmeal',
  'grated cheese',
  'french fries',
  'half-life 2',
  'eggs',
  'tea'],
 ['soup',
  'cake',
  'oatmeal',
  'oil',
  'deodorant',
  'low fat yogurt',
  'muffins',
  'pet food',
  'almonds',
  'cologne',
  'megaman zero',
  'cooking oil',
  'tea'],
 ['soup',
  'cake',
  'oil',
  'airpods',
  'black tea',
  'final fantasy XXII',
  'babies food',
  'white wine',
  'burgers',
  'salt',
  'cooking oil',
  'cauliflower',
  'tea'],
 ['yams', 'oil', 'pasta', 'cooking oil', 'green grapes'],
 ['cotton buds',
  'napkins',
  'zucchini',
  'strong cheese',
  'oil',
  'strawberries',
  'parmesan cheese',
  'muffins',
  'whole weat flour',
  'phone car charger',
  'olive oil',
  'salad',
  'body spray',
  'vacuum cleaner',
  'tea'],
 ['candy bars',
  'tooth brush',
  'cake',
  'strong cheese',
  'mineral water',
  'oil',
  'pokemon sword',
  'mayonnaise',
  'tea'],
 ['frozen smoothie',
  'oil',
  'fromage blanc',
  'burger sauce',
  'vegetables mix',
  'fresh bread',
  'cookies',
  'butter'],
 ['candy bars',
  'soup',
  'napkins',
  'french fries',
  'oil',
  'shower gel',
  'gums',
  'melons',
  'yogurt cake',
  'blueberries',
  'eggs',
  'olive oil'],
 ['cider',
  'soup',
  'dessert wine',
  'cake',
  'soda',
  'shampoo',
  'oil',
  'flax seed',
  'toothpaste',
  'whole weat flour',
  'cream',
  'final fantasy XX',
  'chicken',
  'metroid fusion',
  'tea'],
 ['candy bars',
  'soup',
  'rice',
  'ratchet & clank',
  'gums',
  'cooking oil',
  'tea'],
 ['candy bars',
  'meatballs',
  'turkey',
  'oil',
  'bacon',
  'pokemon scarlet',
  'gums',
  'cookies',
  'tomato juice',
  'barbecue sauce',
  'cooking oil',
  'tea'],
 ['cake',
  'spaghetti',
  'strong cheese',
  'oil',
  'green beans',
  'asparagus',
  'gums',
  'whole weat flour',
  'muffins',
  'cookies',
  'olive oil',
  'cooking oil',
  'tea'],
 ['yams',
  'shower gel',
  'vegetables mix',
  'salmon',
  'mushroom cream sauce',
  'tea'],
 ['tooth brush', 'whole wheat rice', 'oil', 'fresh bread', 'gums', 'tea'],
 ['soup', 'cake', 'soda', 'oil', 'airpods', 'half-life 2', 'portal 2'],
 ['soup', 'oil', 'cereals', 'tea'],
 ['candy bars',
  'cake',
  'airpods',
  'ketchup',
  'oil',
  'light mayo',
  'cooking oil',
  'tea'],
 ['candy bars', 'shower gel', 'tea'],
 ['candy bars',
  'soup',
  'cake',
  'zucchini',
  'rice',
  'french fries',
  'strong cheese',
  'ketchup',
  'laptop',
  'fresh bread',
  'toothpaste',
  'pet food',
  'cookies',
  'megaman zero 4',
  'cooking oil',
  'tea'],
 ['cake',
  'shallot',
  'spaghetti',
  'frozen smoothie',
  'oil',
  'strawberries',
  'ketchup',
  'final fantasy XXII',
  'shrimp',
  'cologne',
  'cooking oil'],
 ['candy bars',
  'bramble',
  'mineral water',
  'shower gel',
  'toothpaste',
  'cream',
  'extra dark chocolate',
  'eggs',
  'cooking oil'],
 ['soda',
  'chutney',
  'oatmeal',
  'strong cheese',
  'french fries',
  'oil',
  'strawberries',
  'shower gel',
  'final fantasy XXII',
  'gums',
  'whole weat flour',
  'almonds',
  'blueberries',
  'spinach',
  'tomato sauce',
  'cooking oil',
  'tea'],
 ['candy bars', 'bacon', 'oil', 'gums', 'yogurt cake', 'cooking oil'],
 ['candy bars', 'grated cheese', 'fromage blanc', 'gums', 'green tea'],
 ['energy bar',
  'mineral water',
  'seabass',
  'oil',
  'melons',
  'cookies',
  'metroid fusion'],
 ['soda', 'oil', 'fresh bread', 'gums', 'cologne', 'cooking oil'],
 ['fresh bread', 'gums', 'pokemon scarlet', 'tea'],
 ['oil',
  'ketchup',
  'airpods',
  'sparkling water',
  'gums',
  'cream',
  'yogurt cake',
  'body spray',
  'cooking oil'],
 ['candy bars',
  'cologne',
  'laptop',
  'oil',
  'low fat yogurt',
  'fresh bread',
  'gums',
  'mayonnaise',
  'white wine',
  'cookies',
  'cooking oil',
  'tea'],
 ['cake',
  'napkins',
  'strong cheese',
  'french fries',
  'oil',
  'avocado',
  'gums',
  'tomatoes',
  'mayonnaise',
  'metroid fusion',
  'cookies',
  'cooking oil',
  'mushroom cream sauce',
  'tea'],
 ['candy bars',
  'cake',
  'napkins',
  'cologne',
  'gums',
  'muffins',
  'yogurt cake',
  'ratchet & clank 3',
  'burgers',
  'megaman zero 4',
  'cooking oil'],
 ['french fries',
  'oil',
  'fresh bread',
  'muffins',
  'yogurt cake',
  'white wine',
  'cologne',
  'megaman zero 4',
  'butter',
  'tea'],
 ['candy bars',
  'cake',
  'oil',
  'ratchet & clank',
  'gums',
  'escalope',
  'half-life: alyx',
  'tomato sauce',
  'cooking oil',
  'tea'],
 ['cereals',
  'ketchup',
  'low fat yogurt',
  'parmesan cheese',
  'pet food',
  'sandwich',
  'cookies',
  'tea'],
 ['candy bars',
  'soup',
  'tooth brush',
  'oatmeal',
  'turkey',
  'fresh bread',
  'toothpaste',
  'milk',
  'muffins',
  'sandwich',
  'toilet paper',
  'salad',
  'cooking oil'],
 ['soup',
  'oatmeal',
  'oil',
  'pasta',
  'cookies',
  'megaman zero 4',
  'red wine',
  'cooking oil',
  'tea'],
 ['chocolate', 'cream', 'trout', 'iMac', 'zucchini'],
 ['cake', 'oil', 'portal', 'yogurt cake', 'pet food'],
 ['soup',
  'cake',
  'napkins',
  'spaghetti',
  'strong cheese',
  'french fries',
  'gadget for tiktok streaming',
  'cereals',
  'final fantasy XXII',
  'extra dark chocolate',
  'olive oil',
  'mint',
  'tea'],
 ['fresh bread', 'napkins', 'tomato sauce', 'tea'],
 ['candy bars',
  'soda',
  'bramble',
  'cottage cheese',
  'turkey',
  'oil',
  'gadget for tiktok streaming',
  'milk',
  'muffins',
  'pet food',
  'cooking oil',
  'tea'],
 ['candy bars', 'cake', 'laptop', 'frozen smoothie', 'fresh bread', 'milk'],
 ['candy bars', 'oil', 'gluten free bar', 'cooking oil', 'cauliflower', 'tea'],
 ['soup', 'napkins', 'oil', 'muffins', 'pasta', 'olive oil', 'barbecue sauce'],
 ['oatmeal',
  'oil',
  'shower gel',
  'pokemon scarlet',
  'milk',
  'hand protein bar',
  'escalope',
  'barbecue sauce',
  'chocolate bread'],
 ['candy bars',
  'cake',
  'oil',
  'shower gel',
  'cream',
  'pasta',
  'green beans',
  'iMac',
  'cooking oil',
  'tea'],
 ['candy bars',
  'cake',
  'oil',
  'fromage blanc',
  'fresh bread',
  'minecraft',
  'babies food',
  'cooking oil'],
 ['final fantasy XIX',
  'soda',
  'cake',
  'mashed potato',
  'oil',
  'bacon',
  'flax seed',
  'cream',
  'babies food',
  'pet food',
  'chili',
  'olive oil',
  'tea'],
 ['cake',
  'spaghetti',
  'mashed potato',
  'oil',
  'milk',
  'burgers',
  'toilet paper',
  'cat food'],
 ['soup',
  'oatmeal',
  'iPad',
  'cottage cheese',
  'oil',
  'toothpaste',
  'cream',
  'gums',
  'olive oil',
  'red wine',
  'tea'],
 ['final fantasy XIX', 'cotton buds', 'napkins', 'chutney', 'tea'],
 ['shampoo',
  'final fantasy XIX',
  'yams',
  'oatmeal',
  'french fries',
  'oil',
  'flax seed',
  'mayonnaise',
  'red wine',
  'herb & pepper'],
 ['energy bar',
  'oil',
  'airpods',
  'strawberries',
  'gums',
  'energy drink',
  'tomato sauce',
  'cooking oil',
  'tea'],
 ['final fantasy XIX',
  'shallot',
  'mashed potato',
  'frozen vegetables',
  'oil',
  'water spray',
  'iMac'],
 ['oatmeal',
  'rice',
  'ring light',
  'cereals',
  'oil',
  'asparagus',
  'shower gel',
  'ratchet & clank',
  'metroid prime',
  'final fantasy XX',
  'body spray',
  'cooking oil',
  'tea'],
 ['cider',
  'soup',
  'barbecue sauce',
  'ketchup',
  'avocado',
  'shower gel',
  'gums',
  'salad',
  'tomato sauce',
  'cooking oil',
  'tea'],
 ['cake',
  'whole wheat rice',
  'napkins',
  'grated cheese',
  'oil',
  'fromage blanc',
  'white wine',
  'eggs',
  'cooking oil'],
 ['oil',
  'fromage blanc',
  'fresh bread',
  'toothpaste',
  'pancakes',
  'pasta',
  'final fantasy XX',
  'half-life: alyx',
  'tea'],
 ['dessert wine',
  'cake',
  'napkins',
  'oil',
  'extra dark chocolate',
  'cooking oil',
  'tea'],
 ['oil',
  'ketchup',
  'gums',
  'parmesan cheese',
  'hand protein bar',
  'olive oil',
  'tomato sauce'],
 ['soup', 'cake', 'napkins', 'oil', 'sparkling water', 'olive oil', 'tea'],
 ['yams',
  'black beer',
  'cake',
  'french fries',
  'dog food',
  'milk',
  'muffins',
  'cooking oil',
  'tea'],
 ['soup',
  'cottage cheese',
  'mineral water',
  'oil',
  'frozen vegetables',
  'final fantasy XXII',
  'ratchet & clank',
  'gums',
  'tomatoes',
  'yogurt cake',
  'cooking oil',
  'tea'],
 ['napkins',
  'oil',
  'fromage blanc',
  'asparagus',
  'vegetables mix',
  'gums',
  'muffins',
  'pasta',
  'half-life 2',
  'cooking oil',
  'tea'],
 ['light cream',
  'napkins',
  'french fries',
  'muffins',
  'cookies',
  'body spray',
  'cooking oil'],
 ['yams', 'oil', 'white wine', 'water spray', 'green grapes'],
 ['cake',
  'napkins',
  'cotton buds',
  'french fries',
  'frozen vegetables',
  'oil',
  'catfish',
  'fresh bread',
  'ratchet & clank',
  'pet food',
  'yogurt cake',
  'phone car charger',
  'cooking oil',
  'tea'],
 ['gluten free bar',
  'shower gel',
  'ratchet & clank',
  'parmesan cheese',
  'babies food',
  'white wine',
  'cooking oil',
  'tea'],
 ['iphone 10',
  'hot dogs',
  'pokemon shield',
  'toothpaste',
  'carrots',
  'muffins',
  'tomatoes',
  'cookies',
  'cooking oil',
  'tea'],
 ['black beer',
  'tooth brush',
  'whole wheat pasta',
  'whole wheat rice',
  'samsung galaxy 10',
  'strong cheese',
  'oil',
  'flax seed',
  'burger sauce',
  'fresh bread',
  'gums',
  'herb & pepper',
  'cooking oil',
  'tea'],
 ['candy bars',
  'whole wheat pasta',
  'oatmeal',
  'barbecue sauce',
  'asparagus',
  'herb & pepper',
  'cooking oil',
  'cauliflower'],
 ['cake', 'cottage cheese', 'oil', 'cream', 'mint green tea', 'tea'],
 ['oil', 'flax seed', 'fresh bread', 'cream', 'cooking oil'],
 ['shampoo',
  'bramble',
  'napkins',
  'mint green tea',
  'strong cheese',
  'oil',
  'bacon',
  'deodorant',
  'fresh bread',
  'gums',
  'muffins',
  'olive oil',
  'butter',
  'cooking oil',
  'tea'],
 ['cake',
  'napkins',
  'spaghetti',
  'oil',
  'milk',
  'muffins',
  'almonds',
  'olive oil',
  'tea'],
 ['candy bars',
  'dessert wine',
  'rice',
  'french fries',
  'minecraft',
  'olive oil',
  'tea'],
 ['soda', 'grated cheese', 'oil', 'mayonnaise', 'yogurt cake'],
 ['cake',
  'megaman zero 3',
  'dog food',
  'sparkling water',
  'final fantasy XXII',
  'fresh tuna',
  'chocolate bread'],
 ['soup',
  'spaghetti',
  'phone charger',
  'french fries',
  'oil',
  'seabass',
  'babies food',
  'corn',
  'half-life: alyx',
  'green beans',
  'cooking oil',
  'tea'],
 ['bramble',
  'oil',
  'tomatoes',
  'muffins',
  'babies food',
  'parmesan cheese',
  'tea'],
 ['pickles', 'oil', 'ham', 'cooking oil'],
 ['oatmeal',
  'cotton buds',
  'oil',
  'ketchup',
  'ratchet & clank',
  'gums',
  'tomatoes',
  'babies food',
  'ratchet & clank 3',
  'body spray',
  'tea'],
 ['candy bars',
  'cake',
  'oatmeal',
  'light cream',
  'oil',
  'airpods',
  'fresh bread',
  'gums',
  'pasta',
  'babies food',
  'melons',
  'cookies',
  'olive oil',
  'cooking oil',
  'tea'],
 ['soup',
  'cake',
  'meatballs',
  'antioxydant juice',
  'spaghetti',
  'french fries',
  'oil',
  'flax seed',
  'gums',
  'pet food',
  'yogurt cake',
  'escalope',
  'olive oil',
  'salad',
  'french wine'],

In [40]:
eclat_algorithm(items_list2, min_combination = 2, max_combination = 2, min_support = 0.02)

Combination 2 by 2

6786it [01:14, 91.36it/s]

                            support
oil & cooking oil          0.428647
tea & oil                  0.426828
cake & oil                 0.329480
tea & cooking oil          0.304542
candy bars & oil           0.261237
...                             ...
napkins & rice             0.020185
shallot & oil              0.020185
tea & deodorant            0.020185
babies food & fresh bread  0.020127
olive oil & ketchup        0.020127

[306 rows x 1 columns]