# **PREPROCESSING NOTEBOOK**

## Libraries

In [1]:
import pandas as pd

## Load Data

In [2]:
customer_info = pd.read_csv('../customer_info.csv', index_col=0)
customer_info.head()

,customer_id,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
0,29930,April Clark,female,01/15/1972 02:27 PM,2.0,2.0,1.0,4.0,7789.0,5601.0,...,1894.0,457.0,412.0,428.0,386.0,0.158741,2018.0,NaN,38.721807,-9.125534
1,6813,Bsc. Paul Ketchum,male,07/31/1944 10:53 AM,0.0,1.0,0.0,4.0,8653.0,35.0,...,346.0,394.0,75.0,226.0,73.0,1.227890,2013.0,971840.0,38.734668,-9.163533
2,39451,Mary Downing,female,11/13/1989 02:11 PM,2.0,3.0,0.0,7.0,15605.0,4275.0,...,1971.0,920.0,335.0,192.0,319.0,0.101598,2011.0,NaN,38.787126,-9.147077
3,21557,Manuel Kueny,male,08/09/1976 06:23 AM,0.0,0.0,1.0,1.0,13440.0,16366.0,...,785.0,139.0,679.0,270.0,221.0,0.259943,2009.0,NaN,38.741816,-9.159700
4,16415,Phd. Curtis Tharp,male,07/11/1966 08:12 AM,1.0,1.0,1.0,5.0,49250.0,3197.0,...,1492.0,1046.0,112.0,144.0,244.0,0.317822,2012.0,925367.0,38.785921,-9.149221

In [3]:
customer_basket = pd.read_csv('../customer_basket.csv')
customer_basket.head()

   invoice_id                                      list_of_goods  customer_id
0     5062209  ['megaman zero 3', 'energy bar', 'pokemon viol...         4925
1     4272512  ['black beer', 'bramble', 'laptop', 'pokemon v...        19046
2     7121052  ['soup', 'shallot', 'cake', 'fresh bread', 'cr...        10318
3     5847748  ['soup', 'cooking oil', 'cereals', 'oil', 'dog...        27283
4     6336114  ['eggplant', 'mint green tea', 'oil', 'bacon',...        16072

## _Customer Info_

### 0. General

In [4]:
print(f'customer_info shape: {customer_info.shape}')

customer_info shape: (34060, 25)

In [32]:
print(f'customer_info main metrics: \n')
customer_info.describe().T

customer_info main metrics:

,count,mean,std,min,25%,50%,75%,max
customer_id,34060.0,20010.854433,11557.889072,1.000000,10018.750000,19985.500000,30042.250000,40000.000000
kids_home,33311.0,1.170244,1.307319,0.000000,0.000000,1.000000,1.000000,10.000000
teens_home,33277.0,0.936292,0.759579,0.000000,0.000000,1.000000,1.000000,4.000000
number_complaints,33038.0,0.832042,0.771205,0.000000,0.000000,1.000000,1.000000,4.000000
distinct_stores_visited,33379.0,2.914078,1.549081,1.000000,2.000000,3.000000,4.000000,10.000000
lifetime_spend_groceries,34060.0,22818.404698,20098.763199,0.000000,9346.000000,15877.500000,30428.250000,158544.000000
lifetime_spend_electronics,34060.0,3816.022343,3858.352640,0.000000,860.000000,2958.000000,5309.000000,37523.000000
typical_hour,32698.0,13.200746,4.681384,6.000000,9.000000,13.000000,16.000000,24.000000
lifetime_spend_vegetables,33038.0,738.642079,679.599323,0.000000,222.000000,451.000000,1089.750000,5380.000000
lifetime_spend_nonalcohol_drinks,34060.0,478.382854,282.132536,0.000000,231.000000,453.000000,661.000000,1702.000000
lifetime_spend_alcohol_drinks,33379.0,838.482998,596.518224,1.000000,347.000000,705.000000,1299.000000,4907.000000
lifetime_spend_meat,34060.0,916.211274,534.330738,0.000000,578.000000,916.000000,1257.000000,3040.000000
lifetime_spend_fish,32357.0,828.842662,655.803300,0.000000,269.000000,714.000000,1269.000000,4043.000000
lifetime_spend_hygiene,34060.0,711.297534,481.230522,0.000000,338.000000,634.000000,1001.000000,3286.000000
lifetime_spend_videogames,34060.0,399.434968,320.221650,0.000000,185.000000,319.000000,506.000000,2176.000000
lifetime_spend_petfood,34060.0,317.755843,150.513835,0.000000,212.000000,313.000000,414.000000,1007.000000
lifetime_total_distinct_products,34060.0,156.691339,118.969652,0.000000,62.000000,122.000000,235.000000,946.000000
percentage_of_products_bought_promotion,34060.0,0.337093,0.322766,-1.340710,0.113353,0.240373,0.514691,1.952971
year_first_transaction,34060.0,2014.593218,4.739037,1995.000000,2011.000000,2015.000000,2018.000000,2026.000000
loyalty_card_number,23152.0,950528.738856,28904.951217,900009.000000,925548.500000,950704.000000,975600.250000,999996.000000
latitude,34060.0,38.747812,0.021562,38.700486,38.730512,38.747755,38.764967,38.793672
longitude,34060.0,-9.156987,0.024561,-9.214894,-9.175987,-9.157015,-9.140522,-9.065429

In [33]:
customer_info.describe(include='object').T

                    count unique                  top   freq
customer_name       34060  33579         Robert Brown      6
customer_gender     34060      2                 male  17133
customer_birthdate  33719  33710  12/23/1956 11:57 PM      2

In [6]:
customer_info.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34060 entries, 0 to 34059
Data columns (total 25 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   customer_id                              34060 non-null  int64
 1   customer_name                            34060 non-null  object
 2   customer_gender                          34060 non-null  object
 3   customer_birthdate                       33719 non-null  object
 4   kids_home                                33311 non-null  float64
 5   teens_home                               33277 non-null  float64
 6   number_complaints                        33038 non-null  float64
 7   distinct_stores_visited                  33379 non-null  float64
 8   lifetime_spend_groceries                 34060 non-null  float64
 9   lifetime_spend_electronics               34060 non-null  float64
 10  typical_hour                             32698 non-null  float64
 11  lifetime_spend_vegetables                33038 non-null  float64
 12  lifetime_spend_nonalcohol_drinks         34060 non-null  float64
 13  lifetime_spend_alcohol_drinks            33379 non-null  float64
 14  lifetime_spend_meat                      34060 non-null  float64
 15  lifetime_spend_fish                      32357 non-null  float64
 16  lifetime_spend_hygiene                   34060 non-null  float64
 17  lifetime_spend_videogames                34060 non-null  float64
 18  lifetime_spend_petfood                   34060 non-null  float64
 19  lifetime_total_distinct_products         34060 non-null  float64
 20  percentage_of_products_bought_promotion  34060 non-null  float64
 21  year_first_transaction                   34060 non-null  float64
 22  loyalty_card_number                      23152 non-null  float64
 23  latitude                                 34060 non-null  float64
 24  longitude                                34060 non-null  float64
dtypes: float64(21), int64(1), object(3)
memory usage: 6.8+ MB

### 1. Duplicates

In [34]:
# Exploration
customer_info_duplicated = customer_info[customer_info.duplicated()]
customer_info_duplicated.head()

Empty DataFrame
Columns: [customer_id, customer_name, customer_gender, customer_birthdate, kids_home, teens_home, number_complaints, distinct_stores_visited, lifetime_spend_groceries, lifetime_spend_electronics, typical_hour, lifetime_spend_vegetables, lifetime_spend_nonalcohol_drinks, lifetime_spend_alcohol_drinks, lifetime_spend_meat, lifetime_spend_fish, lifetime_spend_hygiene, lifetime_spend_videogames, lifetime_spend_petfood, lifetime_total_distinct_products, percentage_of_products_bought_promotion, year_first_transaction, loyalty_card_number, latitude, longitude]
Index: []

[0 rows x 25 columns]

In [8]:
# Treatment

### 2. Outliers

In [9]:
# Exploration

In [10]:
# Treatment

### 3. Missing Values

In [11]:
# Exploration

In [12]:
# Treatment

### 4. Encoding

In [13]:
# Exploration

In [14]:
# Treatment

### 5. Inconsistencies

In [15]:
# Exploration

In [16]:
# Treatment

### 6. Scalling

In [17]:
# Exploration

In [18]:
# Treatment

### 7. Redundancy

In [19]:
# Exploration

In [20]:
# Treatment

## _Customer Basket_

### 0. General

In [24]:
# Explode the list_of_goods column to have one item per row
customer_basket['list_of_goods'] = customer_basket['list_of_goods'].apply(eval)  # Convert string representation of list to actual list
exploded_basket = customer_basket.explode('list_of_goods')

# Group by list_of_goods and count unique invoice_ids and customer_ids
goods_summary = exploded_basket.groupby('list_of_goods').agg(
    invoice_count=('invoice_id', 'nunique'),
    customer_count=('customer_id', 'nunique')
).reset_index()

display(goods_summary)

         list_of_goods  invoice_count  customer_count
0              airpods           7255            5327
1              almonds           3595            3055
2    antioxydant juice           3581            3012
3            asparagus          15906            8220
4              avocado           7150            4979
..                 ...            ...             ...
159  whole wheat pasta           2554            2389
160   whole wheat rice           4377            3798
161               yams           2619            2407
162        yogurt cake           5793            4792
163           zucchini           4739            3834

[164 rows x 3 columns]

In [ ]:
print(f'goods_summary shape: {goods_summary.shape}')

customer_basket shape: (100000, 3)

In [22]:
print(f'goods_summary main metrics: \n')
goods_summary.describe().T

customer_basket main metrics:

,count,mean,std,min,25%,50%,75%,max
invoice_id,100000.0,6.124714e+06,3.533208e+06,20054.0,3066431.5,6118618.0,9195346.75,12242220.0
customer_id,100000.0,1.694557e+04,9.837987e+03,1.0,8425.0,16917.0,25536.00,34060.0

In [29]:
goods_summary.describe(include = 'O').T

              count unique      top freq
list_of_goods   164    164  airpods    1

In [23]:
customer_basket.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 3 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   invoice_id     100000 non-null  int64
 1   list_of_goods  100000 non-null  object
 2   customer_id    100000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 2.3+ MB

### 1. Duplicates

In [35]:
# Exploration
goods_summary_duplicated = goods_summary[goods_summary.duplicated()]
goods_summary_duplicated.head()

Empty DataFrame
Columns: [list_of_goods, invoice_count, customer_count]
Index: []

In [ ]:
# Treatment

### 2. Outliers

In [ ]:
# Exploration

In [ ]:
# Treatment

### 3. Missing Values

In [ ]:
# Exploration

In [ ]:
# Treatment

### 4. Encoding

In [ ]:
# Exploration

In [ ]:
# Treatment

### 5. Inconsistencies

In [ ]:
# Exploration

In [ ]:
# Treatment

### 6. Scalling

In [ ]:
# Exploration

In [ ]:
# Treatment

### 7. Redundancy

In [ ]:
# Exploration

In [ ]:
# Treatment