# **PREPROCESSING NOTEBOOK**

## Libraries

In [1]:
import pandas as pd
import seaborn as sns
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os

# Get the absolute path of the source_code folder
source_code_path = os.path.abspath('../source_code')

# Add the source_code folder to sys.path
if source_code_path not in sys.path:
    sys.path.append(source_code_path)

In [ ]:
from utils import *
from preprocessing import *

## Load Data

In [7]:
customer_info = load_dataset('../customer_info.csv')

In [5]:
customer_info

,customer_id,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
0,29930,April Clark,female,01/15/1972 02:27 PM,2.0,2.0,1.0,4.0,7789.0,5601.0,...,1894.0,457.0,412.0,428.0,386.0,0.158741,2018.0,NaN,38.721807,-9.125534
1,6813,Bsc. Paul Ketchum,male,07/31/1944 10:53 AM,0.0,1.0,0.0,4.0,8653.0,35.0,...,346.0,394.0,75.0,226.0,73.0,1.227890,2013.0,971840.0,38.734668,-9.163533
2,39451,Mary Downing,female,11/13/1989 02:11 PM,2.0,3.0,0.0,7.0,15605.0,4275.0,...,1971.0,920.0,335.0,192.0,319.0,0.101598,2011.0,NaN,38.787126,-9.147077
3,21557,Manuel Kueny,male,08/09/1976 06:23 AM,0.0,0.0,1.0,1.0,13440.0,16366.0,...,785.0,139.0,679.0,270.0,221.0,0.259943,2009.0,NaN,38.741816,-9.159700
4,16415,Phd. Curtis Tharp,male,07/11/1966 08:12 AM,1.0,1.0,1.0,5.0,49250.0,3197.0,...,1492.0,1046.0,112.0,144.0,244.0,0.317822,2012.0,925367.0,38.785921,-9.149221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34055,37071,Mary Diaz,female,01/20/1999 06:47 PM,1.0,1.0,0.0,2.0,62321.0,5250.0,...,1687.0,1048.0,379.0,258.0,163.0,0.162331,2018.0,NaN,38.750813,-9.103808
34056,27422,John Gross,male,08/01/1984 07:50 PM,1.0,1.0,0.0,3.0,16084.0,3796.0,...,568.0,949.0,263.0,319.0,379.0,0.614179,2019.0,985393.0,38.745020,-9.169168
34057,39540,Kathleen Harper,female,09/16/2000 07:22 AM,1.0,0.0,1.0,2.0,14631.0,8784.0,...,1472.0,368.0,804.0,110.0,228.0,0.535617,2018.0,NaN,38.767834,-9.172368
34058,18367,Msc. Jenny Landry,female,04/09/1961 10:52 AM,1.0,1.0,1.0,4.0,37420.0,4702.0,...,904.0,1088.0,401.0,376.0,151.0,0.435014,2015.0,953651.0,38.732462,-9.156155
34059,22050,Roy Wilkins,male,03/25/1993 09:59 PM,2.0,1.0,2.0,1.0,8208.0,38.0,...,618.0,309.0,110.0,471.0,85.0,0.535108,2016.0,NaN,38.747424,-9.155726

In [6]:
customer_basket = load_dataset('../customer_basket.csv')

In [7]:
customer_basket

,invoice_id,list_of_goods,customer_id
0,5062209,"['megaman zero 3', 'energy bar', 'pokemon viol...",4925
1,4272512,"['black beer', 'bramble', 'laptop', 'pokemon v...",19046
2,7121052,"['soup', 'shallot', 'cake', 'fresh bread', 'cr...",10318
3,5847748,"['soup', 'cooking oil', 'cereals', 'oil', 'dog...",27283
4,6336114,"['eggplant', 'mint green tea', 'oil', 'bacon',...",16072
...,...,...,...
99995,5389466,"['frozen smoothie', 'avocado', 'dog food', 'ch...",26170
99996,10387390,"['cake', 'antioxydant juice', 'honey', 'toothp...",19691
99997,7103407,"['candy bars', 'spaghetti', 'oil', 'final fant...",1720
99998,4093515,"['shallot', 'cereals', 'oil', 'deodorant', 'me...",24989
99999,6611217,"['soup', 'napkins', 'pokemon violet', 'ratchet...",482

In [8]:
customer_basket, goods_summary = correct_customer_backet_format(customer_basket)

In [9]:
customer_basket

,invoice_id,list_of_goods,customer_id,number_of_items
0,5062209,"[megaman zero 3, energy bar, pokemon violet, a...",4925,198
1,4272512,"[black beer, bramble, laptop, pokemon violet, ...",19046,179
2,7121052,"[soup, shallot, cake, fresh bread, cream, carr...",10318,142
3,5847748,"[soup, cooking oil, cereals, oil, dog food, de...",27283,149
4,6336114,"[eggplant, mint green tea, oil, bacon, toilet ...",16072,174
...,...,...,...,...
99995,5389466,"[frozen smoothie, avocado, dog food, chili, ch...",26170,108
99996,10387390,"[cake, antioxydant juice, honey, toothpaste, t...",19691,84
99997,7103407,"[candy bars, spaghetti, oil, final fantasy XXI...",1720,118
99998,4093515,"[shallot, cereals, oil, deodorant, metroid pri...",24989,92
99999,6611217,"[soup, napkins, pokemon violet, ratchet & clan...",482,117

In [10]:
goods_summary

         list_of_goods  invoice_count  customer_count
0              airpods           7255            5327
1              almonds           3595            3055
2    antioxydant juice           3581            3012
3            asparagus          15906            8220
4              avocado           7150            4979
..                 ...            ...             ...
159  whole wheat pasta           2554            2389
160   whole wheat rice           4377            3798
161               yams           2619            2407
162        yogurt cake           5793            4792
163           zucchini           4739            3834

[164 rows x 3 columns]

## _Customer Info_

In [11]:
initial_exploration(customer_info)

First few rows of the dataset:

,customer_id,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
0,29930,April Clark,female,01/15/1972 02:27 PM,2.0,2.0,1.0,4.0,7789.0,5601.0,...,1894.0,457.0,412.0,428.0,386.0,0.158741,2018.0,NaN,38.721807,-9.125534
1,6813,Bsc. Paul Ketchum,male,07/31/1944 10:53 AM,0.0,1.0,0.0,4.0,8653.0,35.0,...,346.0,394.0,75.0,226.0,73.0,1.227890,2013.0,971840.0,38.734668,-9.163533
2,39451,Mary Downing,female,11/13/1989 02:11 PM,2.0,3.0,0.0,7.0,15605.0,4275.0,...,1971.0,920.0,335.0,192.0,319.0,0.101598,2011.0,NaN,38.787126,-9.147077
3,21557,Manuel Kueny,male,08/09/1976 06:23 AM,0.0,0.0,1.0,1.0,13440.0,16366.0,...,785.0,139.0,679.0,270.0,221.0,0.259943,2009.0,NaN,38.741816,-9.159700
4,16415,Phd. Curtis Tharp,male,07/11/1966 08:12 AM,1.0,1.0,1.0,5.0,49250.0,3197.0,...,1492.0,1046.0,112.0,144.0,244.0,0.317822,2012.0,925367.0,38.785921,-9.149221

Shape of the dataset:
(34060, 25)

data types of each column:
customer_id                                  int64
customer_name                               object
customer_gender                             object
customer_birthdate                          object
kids_home                                  float64
teens_home                                 float64
number_complaints                          float64
distinct_stores_visited                    float64
lifetime_spend_groceries                   float64
lifetime_spend_electronics                 float64
typical_hour                               float64
lifetime_spend_vegetables                  float64
lifetime_spend_nonalcohol_drinks           float64
lifetime_spend_alcohol_drinks              float64
lifetime_spend_meat                        float64
lifetime_spend_fish                        float64
lifetime_spend_hygiene                     float64
lifetime_spend_videogames                  float64
lifetime_spend_petfood                     float64
lifetime_total_distinct_products           float64
percentage_of_products_bought_promotion    float64
year_first_transaction                     float64
loyalty_card_number                        float64
latitude                                   float64
longitude                                  float64
dtype: object

Basic statistics of the dataset:

,count,mean,std,min,25%,50%,75%,max
customer_id,34060.0,20010.854433,11557.889072,1.000000,10018.750000,19985.500000,30042.250000,40000.000000
kids_home,33311.0,1.170244,1.307319,0.000000,0.000000,1.000000,1.000000,10.000000
teens_home,33277.0,0.936292,0.759579,0.000000,0.000000,1.000000,1.000000,4.000000
number_complaints,33038.0,0.832042,0.771205,0.000000,0.000000,1.000000,1.000000,4.000000
distinct_stores_visited,33379.0,2.914078,1.549081,1.000000,2.000000,3.000000,4.000000,10.000000
lifetime_spend_groceries,34060.0,22818.404698,20098.763199,0.000000,9346.000000,15877.500000,30428.250000,158544.000000
lifetime_spend_electronics,34060.0,3816.022343,3858.352640,0.000000,860.000000,2958.000000,5309.000000,37523.000000
typical_hour,32698.0,13.200746,4.681384,6.000000,9.000000,13.000000,16.000000,24.000000
lifetime_spend_vegetables,33038.0,738.642079,679.599323,0.000000,222.000000,451.000000,1089.750000,5380.000000
lifetime_spend_nonalcohol_drinks,34060.0,478.382854,282.132536,0.000000,231.000000,453.000000,661.000000,1702.000000
lifetime_spend_alcohol_drinks,33379.0,838.482998,596.518224,1.000000,347.000000,705.000000,1299.000000,4907.000000
lifetime_spend_meat,34060.0,916.211274,534.330738,0.000000,578.000000,916.000000,1257.000000,3040.000000
lifetime_spend_fish,32357.0,828.842662,655.803300,0.000000,269.000000,714.000000,1269.000000,4043.000000
lifetime_spend_hygiene,34060.0,711.297534,481.230522,0.000000,338.000000,634.000000,1001.000000,3286.000000
lifetime_spend_videogames,34060.0,399.434968,320.221650,0.000000,185.000000,319.000000,506.000000,2176.000000
lifetime_spend_petfood,34060.0,317.755843,150.513835,0.000000,212.000000,313.000000,414.000000,1007.000000
lifetime_total_distinct_products,34060.0,156.691339,118.969652,0.000000,62.000000,122.000000,235.000000,946.000000
percentage_of_products_bought_promotion,34060.0,0.337093,0.322766,-1.340710,0.113353,0.240373,0.514691,1.952971
year_first_transaction,34060.0,2014.593218,4.739037,1995.000000,2011.000000,2015.000000,2018.000000,2026.000000
loyalty_card_number,23152.0,950528.738856,28904.951217,900009.000000,925548.500000,950704.000000,975600.250000,999996.000000
latitude,34060.0,38.747812,0.021562,38.700486,38.730512,38.747755,38.764967,38.793672
longitude,34060.0,-9.156987,0.024561,-9.214894,-9.175987,-9.157015,-9.140522,-9.065429

Missing values in each column:
customer_id                                    0
customer_name                                  0
customer_gender                                0
customer_birthdate                           341
kids_home                                    749
teens_home                                   783
number_complaints                           1022
distinct_stores_visited                      681
lifetime_spend_groceries                       0
lifetime_spend_electronics                     0
typical_hour                                1362
lifetime_spend_vegetables                   1022
lifetime_spend_nonalcohol_drinks               0
lifetime_spend_alcohol_drinks                681
lifetime_spend_meat                            0
lifetime_spend_fish                         1703
lifetime_spend_hygiene                         0
lifetime_spend_videogames                      0
lifetime_spend_petfood                         0
lifetime_total_distinct_products               0
percentage_of_products_bought_promotion        0
year_first_transaction                         0
loyalty_card_number                        10908
latitude                                       0
longitude                                      0
dtype: int64

### 1. Duplicates

In [12]:
# Exploration
check_duplicates(customer_info)

Number of duplicate rows: 0

0

In [13]:
# Treatment
customer_info = treat_duplicates(customer_info)

Duplicates have been removed.

### 2. Outliers

In [ ]:
# Exploration

In [ ]:
# Treatment

### 3. Missing Values

In [ ]:
# Exploration
customer_info.info()

In [ ]:
customer_info.describe().T

In [ ]:
# Treatment
customer_info.isnull().sum()

In [ ]:
#cannot impute for customer_birthdate and loylty_card_number

In [ ]:
# Treatment

### 4. Encoding

In [ ]:
# Exploration

In [ ]:
# Treatment

### 5. Inconsistencies

In [ ]:
# Exploration

In [ ]:
# Treatment

### 6. Scalling

In [ ]:
# Exploration

In [ ]:
# Treatment

### 7. Redundancy

In [ ]:
# Exploration

In [ ]:
# Treatment

## _Customer Basket_

In [ ]:
initial_exploration(customer_basket)

### 1. Duplicates

In [ ]:
# Exploration
check_duplicates(customer_basket)

In [ ]:
# Treatment

### 1. Duplicates

In [ ]:
# Exploration
check_duplicates(customer_basket)

In [ ]:
# Treatment
customer_basket = treat_duplicates(customer_basket)

### 2. Outliers

In [ ]:
# Exploration

In [ ]:
# Treatment

### 3. Missing Values

In [ ]:
# Exploration

In [ ]:
# Treatment

### 4. Encoding

In [ ]:
# Exploration

In [ ]:
# Treatment

### 5. Inconsistencies

In [ ]:
# Exploration

In [ ]:
# Treatment

### 6. Scalling

In [ ]:
# Exploration

In [ ]:
# Treatment

### 7. Redundancy

In [ ]:
# Exploration

In [ ]:
# Treatment