# **PREPROCESSING NOTEBOOK**

## Libraries

In [1]:
import pandas as pd
import seaborn as sns
%load_ext autoreload
%autoreload 2

In [2]:
from source_code.utils import *
from source_code.preprocessing import *

ModuleNotFoundError: No module named 'source_code'

## Load Data

In [6]:
customer_info = load_dataset('../customer_info.csv')

NameError: name 'load_dataset' is not defined

In [ ]:
customer_basket = load_dataset('../customer_basket.csv')

## _Customer Info_

In [ ]:
initial_exploration(customer_info)

### 1. Duplicates

In [ ]:
# Exploration
check_duplicates(customer_info)

Empty DataFrame
Columns: [customer_id, customer_name, customer_gender, customer_birthdate, kids_home, teens_home, number_complaints, distinct_stores_visited, lifetime_spend_groceries, lifetime_spend_electronics, typical_hour, lifetime_spend_vegetables, lifetime_spend_nonalcohol_drinks, lifetime_spend_alcohol_drinks, lifetime_spend_meat, lifetime_spend_fish, lifetime_spend_hygiene, lifetime_spend_videogames, lifetime_spend_petfood, lifetime_total_distinct_products, percentage_of_products_bought_promotion, year_first_transaction, loyalty_card_number, latitude, longitude]
Index: []

[0 rows x 25 columns]

In [ ]:
# Treatment
customer_info = treat_duplicates(customer_info)

### 2. Outliers

In [10]:
# Exploration

In [11]:
# Treatment

### 3. Missing Values

In [12]:
# Exploration
customer_info.info()

In [13]:
customer_info.describe().T

In [14]:
# Treatment
customer_info.isnull().sum()

In [15]:
#cannot impute for customer_birthdate and loylty_card_number

In [17]:
# Treatment

### 4. Encoding

In [ ]:
# Exploration

In [ ]:
# Treatment

### 5. Inconsistencies

In [ ]:
# Exploration

In [ ]:
# Treatment

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 3 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   invoice_id     100000 non-null  int64
 1   list_of_goods  100000 non-null  object
 2   customer_id    100000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 2.3+ MB

### 6. Scalling

In [18]:
# Exploration

In [19]:
# Treatment

### 7. Redundancy

In [20]:
# Exploration

In [21]:
# Treatment

## _Customer Basket_

In [ ]:
initial_exploration(customer_basket)

### 1. Duplicates

In [ ]:
# Exploration
check_duplicates(customer_basket)

Empty DataFrame
Columns: [customer_id, customer_name, customer_gender, customer_birthdate, kids_home, teens_home, number_complaints, distinct_stores_visited, lifetime_spend_groceries, lifetime_spend_electronics, typical_hour, lifetime_spend_vegetables, lifetime_spend_nonalcohol_drinks, lifetime_spend_alcohol_drinks, lifetime_spend_meat, lifetime_spend_fish, lifetime_spend_hygiene, lifetime_spend_videogames, lifetime_spend_petfood, lifetime_total_distinct_products, percentage_of_products_bought_promotion, year_first_transaction, loyalty_card_number, latitude, longitude]
Index: []

[0 rows x 25 columns]

In [ ]:
# Treatment

### 1. Duplicates

In [ ]:
# Exploration
check_duplicates(customer_basket)

Empty DataFrame
Columns: [list_of_goods, invoice_count, customer_count]
Index: []

In [ ]:
# Treatment
customer_basket = treat_duplicates(customer_basket)

### 2. Outliers

In [29]:
# Exploration

In [30]:
# Treatment

### 3. Missing Values

In [31]:
# Exploration

In [32]:
# Treatment

### 4. Encoding

In [33]:
# Exploration

In [34]:
# Treatment

### 5. Inconsistencies

In [35]:
# Exploration

In [36]:
# Treatment

### 6. Scalling

In [37]:
# Exploration

In [38]:
# Treatment

### 7. Redundancy

In [39]:
# Exploration

In [40]:
# Treatment